packages/ubuntu_init/.metadata
packages/ubuntu_init/lib/main.dart
packages/ubuntu_init/lib/src/services/xdg_keyboard_service.dart
packages/ubuntu_init/linux/.gitignore
packages/ubuntu_init/linux/CMakeLists.txt
packages/ubuntu_init/linux/flutter/CMakeLists.txt
packages/ubuntu_init/linux/main.cc
packages/ubuntu_init/linux/my_application.cc
packages/ubuntu_init/linux/my_application.h
packages/ubuntu_init/pubspec.yaml
packages/ubuntu_init/test/services/xdg_keyboard_service_test.dart

Mainly for development and testing purposes.
Note: the asset lookup in xdg_keyboard_service had to be tweaked so that it's able to look up assets either from the app or from the ubuntu_init package.

feat(init): add app runner for ubuntu_init

---

packages/ubuntu_bootstrap/lib/services/timezone_service.dart
packages/ubuntu_bootstrap/test/services/timezone_service_test.dart
packages/ubuntu_init/lib/src/services/xdg_timezone_service.dart
packages/ubuntu_init/test/services/xdg_timezone_service_test.dart
packages/ubuntu_provision/lib/src/services/timezone_service.dart
packages/ubuntu_provision/lib/src/timezone/timezone_model.dart
packages/ubuntu_provision/test/timezone/timezone_model_test.dart

While 'geoip' is the desired default for Subiquity, it's not a valid value for XDG so default to 'Etc/UTC' instead.
```
The following DBusInvalidArgsException was thrown running a test:
org.freedesktop.DBus.Error.InvalidArgs: Invalid or not installed time zone 'geoip'
```

fix(timezone): fix XDG default

---

packages/ubuntu_provision_test/.gitignore
packages/ubuntu_provision_test/.metadata
packages/ubuntu_provision_test/lib/ubuntu_provision_test.dart
packages/ubuntu_provision_test/pubspec.yaml

Allow various integration tests, even outside this repo, to easily run bootstrap and init wizards.
See also:
- #12

test: promote udi/integration_test/test_pages

---

packages/ubuntu_init/lib/src/services/xdg_identity_service.dart
packages/ubuntu_init/lib/src/services/xdg_keyboard_service.dart
packages/ubuntu_init/lib/src/services/xdg_locale_service.dart
packages/ubuntu_init/lib/src/services/xdg_timezone_service.dart
packages/ubuntu_init/test/services/xdg_identity_service_test.dart
packages/ubuntu_init/test/services/xdg_keyboard_service_test.dart
packages/ubuntu_init/test/services/xdg_locale_service_test.dart
packages/ubuntu_init/test/services/xdg_timezone_service_test.dart
packages/ubuntu_provision/lib/src/services/network_service.dart
packages/ubuntu_provision/lib/src/services/theme_service.dart
packages/ubuntu_provision/test/services/theme_service_test.dart
packages/ubuntu_provision/test/test_utils.mocks.dart

Follow the same convention as Canonical's dbus.dart-based libraries that allow optionally passing a named `{DBusClient? bus}` property to client constructors. This allows using a fake D-Bus server for integration testing and easily passing the appropriate bus to all services without having to deal with XdgLocaleClient, GSettings, and friends. In this scenario, all services and clients are real, only the server side is fake.
```dart
final server = FakeDBusServer();
final client = DBusClient(await server.start(...));
registerService<IdentityService>(() => XdgIdentityService.uid(0, bus: client));
registerService<KeyboardService>(() => XdgKeyboardService(bus: client));
registerService<LocaleService>(() => XdgLocaleService(bus: client));
registerService<NetworkService>(() => …
```

refactor(init): tweak XDG services

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/pubspec.yaml
packages/ubuntu_init/lib/src/init_services.dart
packages/ubuntu_init/lib/src/services/xdg_keyboard_service.dart
packages/ubuntu_provision/lib/src/services/desktop_service.dart
packages/ubuntu_provision/lib/src/services/theme_service.dart

Allows wiring up custom D-Bus clients and keyfile backends for GSettings for testing purposes.
GSettings is somewhat complicated because it writes through DConf's D-Bus API but reads directly from the file system. Even though `gsettings.dart` allows setting environment variables for customization, this is not usable in tests because the immutable `Platform.environment` is already accessed and cached before the test entry point gets called so it's too late to set any environment variables at the beginning of tests.
See also:
- #19

refactor: register GSettings factory

---

packages/ubuntu_init/lib/src/init_wizard.dart

Calling asynchronous `InitModel.init()` from within `InitWizard.initState()` leaves the future dangling. Make use of `WizardRoute.onReplace` from the initial loading route to ensure that the initialization routine finishes before proceeding to the next route.

fix(init): model initialization on startup

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_init/lib/src/init_services.dart
packages/ubuntu_init/test/init_services_test.dart
packages/ubuntu_provision/lib/src/services/config_service.dart
packages/ubuntu_provision/pubspec.yaml
packages/ubuntu_provision/test/services/config_service_test.dart

Unless `--config <path>` is passed, look up the config file path in the following order:
- `/etc/ubuntu-provision.{conf,yaml,yml}` (admin)
- `/usr/local/share/ubuntu-provision.{conf,yaml,yml}` (oem)
- `/usr/share/ubuntu-provision.{conf,yaml,yml}` (distro)
Notes:
- The standard [XDG config and data dirs](https://pub.dev/packages/xdg_directories) are supported.
- To limit the amount of FS checks, only a subset of the supported extensions are looked up.
Ref: canonical/ubuntu-desktop-installer#2194

feat(config): look up the config file unless explicitly specified

---

.github/workflows/ci.yml
melos.yaml

- Run coverage jobs in parallel. The downside is to have to list them in the matrix but on the upside, they only take a few minutes each.
- Run all tests without coverage collection to ensure no test gets skipped if they are forgotten from the manually maintained coverage matrix. Executing all tests without coverage collection doesn't take much longer than it takes to run the longest test with coverage collection.
- Ignore `subiquity_client` & `subiquity_test` units tests because they are already run at [subiquity_client.dart](https://github.com/canonical/subiquity_client.dart). This saves us from installing subiquity dependencies for running unit tests.

chore: optimize melos & ci

---

packages/ubuntu_utils/lib/src/proxy_asset_bundle.dart
packages/ubuntu_utils/test/proxy_asset_bundle_test.dart

`ubuntu_bootstrap` can run as a standalone app or be used as a library. In the former case, `ubuntu_bootstrap`'s own assets (e.g. on the installation slides) must be looked up from `<bundle>/assets/` whereas in the latter case, they must be looked up from `<bundle>/packages/ubuntu_bootstrap/assets/`.
The problem came up in #35 while trying to run integration tests for `ubuntu_bootstrap`. The issue is easy to reproduce by simply running `ubuntu_bootstrap` as a standalone app and navigating until the installation slides:
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: "packages/ubuntu_bootstrap/assets/slides/mascot.png".
The asset does not exist or has …
```

fix(utils): fix app vs. package asset lookup

---

packages/ubuntu_provision/lib/src/services/journal_service.dart
packages/ubuntu_provision/test/services/journal_service_test.dart

In Dart, generator streams are always single-subscription streams, even if it yields a broadcast stream, and a single-subscription stream does not allow closing and re-subscribing.
The journal stream for the log view must be a broadcast stream to be able to resubscribe in case of state changes and rebuilds. The issue was noticed in #35:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building _JournalView(dependencies: [_InheritedTheme,
_LocalizationsScope-[GlobalKey#05e92]]):
Bad state: Stream has already been listened to.
The relevant error-causing widget was:
_JournalView
_JournalView:file:///home/runner/work/ubuntu-desktop-provision/ubuntu-desktop-provision/packages/ubuntu_bootstrap/lib/pages/i …
```

fix(provision): broadcast journal stream

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/lib/services/installer_service.dart
packages/ubuntu_bootstrap/test/installer_wizard_test.dart
packages/ubuntu_bootstrap/test/services/installer_service_test.dart
packages/ubuntu_init/integration_test/ubuntu_init_test.dart
packages/ubuntu_init/lib/src/init_model.dart
packages/ubuntu_init/lib/src/init_services.dart
packages/ubuntu_init/test/init_model_test.dart
packages/ubuntu_init/test/init_wizard_test.dart

The term "page" is more user-friendly and matches with GIS, whereas "route" basically refers to an implementation detail.

refactor(config): rename 'routes' to 'pages'

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_init/lib/src/init_services.dart
packages/ubuntu_init/test/init_model_test.mocks.dart
packages/ubuntu_provision/lib/src/services/config_service.dart
packages/ubuntu_provision/test/services/config_service_test.dart
packages/ubuntu_provision/test/test_utils.mocks.dart

Makes it possible to run different wizard stages with the same config:
```ini
[bootstrap]
pages = ...
[init]
pages = ...
```

feat(config): introduce bootstrap & init scopes

---

packages/ubuntu_provision/lib/src/services/config_service.dart
packages/ubuntu_provision/test/services/config_service_test.dart

If nothing else is configured on the system, allow specific `ubuntu_bootstrap` or `ubuntu_init` builds to configure which pages they should show by default.

feat(config): allow apps to ship default config asset

---

packages/ubuntu_provision/lib/src/services/config_service.dart
packages/ubuntu_provision/test/services/config_service_test.dart

We'll copy a config file into `assets/` during snapcraft build process. `ubuntu_bootstrap` and `ubuntu_init` will automatically pick it from there as they both have:
```yaml
flutter:
assets:
- assets/
```

fix(config): add missing `assets/` subdir

---

packages/ubuntu_bootstrap/lib/services/installer_service.dart
packages/ubuntu_bootstrap/test/services/installer_service_test.dart
packages/ubuntu_init/lib/src/init_model.dart
packages/ubuntu_init/test/init_model_test.dart

Allow "foo,bar" instead of ["foo", "bar"] for convenience.

feat(config): allow passing pages as comma-delimited string

---

packages/ubuntu_provision/lib/src/theme/theme_page.dart
packages/ubuntu_wizard/lib/src/wizard_button.dart

No individual pages should have to force-enable Next/Done. Any page could be configured as the last page. It must be possible to click Done to finish the wizard and close the window even if there's no next page route.

fix(wizard): don't disable the last next/done button

---

packages/ubuntu_provision_test/lib/src/bootstrap_tester.dart
packages/ubuntu_provision_test/lib/src/provision_tester.dart
packages/ubuntu_provision_test/lib/src/wizard_tester.dart
packages/ubuntu_provision_test/lib/ubuntu_provision_test.dart

Split `page_tester.dart` into smaller pieces and expose more helpers for UDI:
- `bootstrap_tester.dart` with `testXxxPage()` for bootstrap-specific pages
- `provision_tester.dart` with `testXxxPage()` for common provisioning pages
- `wizard_tester.dart` with `tapXxx()` and `takeScreenshot()` etc. helpers (previously unexposed, needed by udi/screenshot_test).

refactor: ubuntu_provision_test for UDI

---

packages/ubuntu_bootstrap/lib/installer.dart

For example:
```sh
$ ubuntu_bootstrap \
--source-catalog=examples/sources/tpm.yaml \
--dry-run-config examples/dry-run-configs/tpm.yaml
```
Manually cherry-picked from [udi/canary-23.10](https://github.com/canonical/ubuntu-desktop-installer/commit/509ac2b7647eecc01eadfb08a8dfcb52c3028e2c).

feat: add --dry-run-config CLI argument

---

packages/ubuntu_bootstrap/integration_test/ubuntu_bootstrap_test.dart
packages/ubuntu_bootstrap/lib/pages/storage/security_key/security_key_model.dart
packages/ubuntu_bootstrap/lib/pages/storage/storage_dialogs.dart
packages/ubuntu_bootstrap/test/storage/storage_dialogs_test.dart
packages/ubuntu_bootstrap/test/storage/storage_page_test.dart
packages/ubuntu_provision_test/lib/src/bootstrap_tester.dart

Restores the old ZFS selection that has been commented out since 2021, and wires it up with `GuidedCapability.ZFS` recently introduced in Subiquity.
Original design: https://people.canonical.com/~platform/desktop/installer/8.%20Installation%20Type/#artboard2
Close: https://github.com/canonical/ubuntu-desktop-installer/issues/417

feat(bootstrap): zfs

---

packages/ubuntu_bootstrap/lib/pages/storage/recovery_key/recovery_key_model.dart

Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>
(cherry picked from ubuntu_desktop_installer commit f4c79e57d47acec293ea7d70e78438eb080434b6)
/cc @ogayot

fix: typo in shown command to retrieve recovery key (#2282)

---

packages/sysmetrics/lib/src/sysmetrics.dart

It takes a significant amount of time to collect the data. Hide the FFI calls into isolates rather than forcing the telemetry view model to do that because it makes the sysmetrics calls non-mockable/verifiable.
[Screencast from 2023-08-08 14-09-47.webm](https://github.com/canonical/ubuntu-desktop-provision/assets/140617/4d39ba62-5785-42e2-b7e8-9aa5056921f6)
Ref: #42

refactor(sysmetrics): move blocking FFI calls into isolates

---

packages/ubuntu_bootstrap/lib/pages/storage/storage_model.dart
packages/ubuntu_bootstrap/lib/pages/storage/storage_page.dart
packages/ubuntu_bootstrap/test/storage/storage_page_test.dart
packages/ubuntu_bootstrap/test/storage/test_storage.dart
packages/ubuntu_bootstrap/test/storage/test_storage.mocks.dart

DD targets are handled the same way as other reformat targets. Additionally, advanced features are only offered if appropriate.
```
$ ubuntu_bootstrap --source-catalog=examples/sources/core.yaml
```

feat(bootstrap): add minimal changes for dd targets

---

packages/ubuntu_provision_test/lib/src/fake_init.dart

Make sure `ubuntu_init/screenshot_test` produces stable screenshots. It should not use the actual host product version because it could change from time to time and cause bogus updates:
- https://github.com/canonical/ubuntu-desktop-provision-screenshots/pull/186
[Screencast from 2023-08-09 14-12-45.webm](https://github.com/canonical/ubuntu-desktop-provision/assets/140617/0c40eeaf-4631-4558-993a-512412275098)
With this change, it'll be:

test(init): register a fake product for screenshots

---

packages/ubuntu_bootstrap/integration_test/screenshot_test.dart
packages/ubuntu_init/integration_test/screenshot_test.dart

To fix sorting here and there, including GitHub where people often browse these screenshots:

chore(test): add leading zeros to screenshot numbers

---

packages/ubuntu_init/lib/src/init_app.dart

I missed that `ubuntu-welcome` has its own localized app title that it must pass in to be able to use `runInitApp()`.

feat(init): allow passing app title & l10n delegates to runInitApp()

---

packages/ubuntu_init/lib/src/store/store_model.dart
packages/ubuntu_init/test/store/store_model_test.dart

`canLaunchUrl()` doesn't work from a confined snap even if `launchUrl()` does.

fix(store): remove can-launch check

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/pubspec.yaml
packages/ubuntu_init/lib/src/init_app.dart
packages/ubuntu_init/pubspec.yaml
packages/ubuntu_provision/lib/flavor.dart
packages/ubuntu_wizard/lib/src/wizard_app.dart
packages/ubuntu_wizard/lib/src/wizard_theme.dart
packages/ubuntu_wizard/pubspec.yaml

Even if [ubuntu_flavor](https://pub.dev/packages/ubuntu_flavor) is able to detect most official Ubuntu flavors, there needs to be a way to pass a specific flavor for being able to:
- lock down a specific flavor regardless of the host platform (ubuntu-xxx-installer should always run as xxx)
- pass an imaginary custom flavor for demoing purposes (ubuntu-flavor-installer)

feat(flavors): restore the ability to pass flavor data

---

packages/ubuntu_bootstrap/lib/installer.dart

Same as #82 but for ubuntu_bootstrap, needed for flavors' translated installations slides.

fix(bootstrap): expose missing l10n arguments for runInstallerApp()

---

packages/ubuntu_bootstrap/lib/pages/source/source_page.dart

Sources are a radio button and it should not be displayed if there is just one source. In this case we go with the default.
closes: https://github.com/canonical/ubuntu-desktop-installer/issues/2305

fix: Only show installation sources if there is more than one

---

packages/ubuntu_bootstrap/integration_test/ubuntu_bootstrap_test.dart
packages/ubuntu_bootstrap/lib/pages/storage/security_key/security_key_model.dart

This option is not yet supported in subiquity and must not be displayed.
closes: https://github.com/canonical/ubuntu-desktop-installer/issues/2311

fix: Do not show the security key page for ZFS

---

packages/ubuntu_bootstrap/lib/pages/storage/storage_model.dart

Before https://github.com/canonical/subiquity/pull/1774 the order of the capabilities in `allowed` was arbitrary, resulting in https://bugs.launchpad.net/ubuntu-desktop-installer/+bug/2033093 and other confusing behaviour. The subiquity PR puts the capability that should be considered the default first, so that's what the client side code should do too.

take first capability from allowed as default

---

packages/ubuntu_init/lib/src/services/xdg_identity_service.dart
packages/ubuntu_init/pubspec.yaml
packages/ubuntu_init/test/services/xdg_identity_service_test.dart

The method org.freedesktop.Accounts.User.SetPassword expects a crypted password as its first parameter. Unfortunately, the current code is sending the password in plain text. That plain text password is being stored as-is in the 'shadow' file, and that prevents ubuntu-core-desktop-init to work on core desktop, because the created user has an invalid password field.
This patch fixes it.

fix: DBus SetPassword method expects a crypted pass 

---

packages/ubuntu_bootstrap/lib/installer.dart

UDENG-1423
Fix https://github.com/canonical/ubuntu-desktop-installer/issues/2342.
The `path` parameter in `Logger.setup()` from `ubuntu_logger` is supposed to be the path to the actual log file, not the directory containing it.

fix(logging): specify path to log file, not directory

---

packages/ubuntu_bootstrap/lib/slides/default_slides.dart

* Lists LibreOffice Writer as 'available' instead of 'included'
* Moves Language Support and Orca Screen Reader to the first row

feat(slides): update accessibility slide

---

packages/ubuntu_bootstrap/integration_test/screenshot_test.dart
packages/ubuntu_bootstrap/test/installer_test.dart

I noticed that #131 introduced a test failure due to a missing mock for the `NetworkService`

fix(test): add missing MockNetworkService

---

CONTRIBUTING.md

Updates the contribution guidelines, using [our template](https://github.com/canonical/desktop-engineering/blob/main/project-repo/templates/common/CONTRIBUTING.md) as a starting point.
I've left out the issue reporting section, since we'll probably need to rethink that process first (currently there's [launchpad](https://bugs.launchpad.net/ubuntu-desktop-installer/), the issue tracker at [ubuntu-desktop-installer](https://github.com/canonical/ubuntu-desktop-installer/issues) and the one in this repo [here](https://github.com/canonical/ubuntu-desktop-provision/issues)).
I've also left out the section on how to build/run the binaries for now. The two binaries that can currently be built are `ubuntu_bootstrap` and `ubuntu_init`, while the rest of the packages are pure libraries. Maybe it's a …

feat: update CONTRIBUTING.md

---

melos.yaml
packages/ubuntu_bootstrap/pubspec.yaml
packages/ubuntu_init/pubspec.yaml
packages/ubuntu_provision/pubspec.yaml
packages/ubuntu_provision_test/pubspec.yaml
packages/ubuntu_wizard/pubspec.yaml

Let's pin the yaru versions for now to fix the [recent test failures](https://github.com/canonical/ubuntu-desktop-provision/actions/runs/6893487495/job/18753168310) caused by yaru 1.2.0.
Yaru folks: in case you're reading this, I'm not blaming you and don't know what the actual bug is since I can't reproduce it locally - but pinning yaru to 1.1.0 seems to solve it. Might be a bug in ubuntu_wizard though.
@spydon are there any other package versions we should pin?

feat: pin yaru versions

---

.github/dependabot.yaml

Adding clauses to the `dependabot.yaml` to support checking go & gh-action deps
Closes #208

ci(dependabot): update to support go subproject

---

.github/dependabot.yaml

Looking at the options for the [allow](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) clause, production makes the most sense to me as the dependencies to keep monitored, seeing as we aren't directly working on `subiquity` in this monorepo.

fix(ci): fixing dependency type

---

scripts/inject-snap
scripts/subiquity_integration
scripts/update-subiquity-deps
snap/local/launcher
snap/local/postinst.d/10_configure_auto_login
snap/local/postinst.d/10_copy_bluetooth_config
snap/local/postinst.d/10_copy_network_config
snap/local/postinst.d/10_flash_kernel
snap/local/postinst.d/10_override_desktop_settings
snap/local/postinst.d/50_zfs_cache
snap/local/postinst.d/99_telemetry_done
snap/local/subiquity-server
snap/local/ubuntu-desktop-installer.desktop
snap/snapcraft.yaml

Adds the `snapcraft.yaml` from ubuntu-desktop-installer including post-installation scripts and everything else that's needed to build a working snap directly from `ubuntu_bootstrap`.
Note that this PR targets the `bootstrap-snap` branch, which is supposed to track `main` while carrying along everything that's needed to build and maintain the ubuntu-desktop-installer snap. I'll open a separate PR that adds a github action to build a snap in the CI whenever we push to this branch.
P.S. [here](https://github.com/d-loose/ubuntu-desktop-provision/actions/runs/6890839054/job/18744678019)'s a test build I ran using this setup.
UDENG-1750
Fix: #196

feat: add snapcraft.yaml to build ubuntu-desktop-installer snap from ubuntu_bootstrap

---

.github/workflows/snap.yaml

Adds a workflow that builds a snap from the `bootstrap-snap` branch whenever we push to it. Also includes `workflow_dispatch` to manually trigger snap builds.
I'd merge this one first and rebase #193 onto it once we're happy with it.

feat(ci): add snap workflow for the installer/ubuntu-desktop-bootstrap

---

.github/workflows/ci.yml
.github/workflows/snap.yaml

We don't need to run the Flutter and Go tests on the snap branch - instead just run the snap workflow there.
I'd open a PR that merges `main` into `bootstrap-snap` afterwards.
P.S. I've also removed the obsolete `canary-*` and `ubuntu/**` branches

feat(ci): run tests only on main and archive/main

---

.github/workflows/snap.yaml

Same as for the `bootstrap-snap` branch

feat(ci): build snap on init-snap branch

---

snap/local/ubuntu-desktop-init.desktop
snap/snapcraft.yaml

Adds a snap for ubuntu-desktop-init based on https://github.com/canonical/ubuntu-welcome/.
I've removed the custom launcher that's being used as a workaround to put a `.config/ubuntu-welcome-done` file into the user's home directory in ubuntu-welcome. We can add something like this back in later if needed, but we'd need to modify ubuntu-init accordingly first.

feat: add snapcraft.yaml for ubuntu-desktop-init

---

.github/workflows/ci.yml

flutter-tests runs `melos coverage`, so the flutter-coverage job is now redundant.
It was originally introduced in https://github.com/canonical/ubuntu-desktop-provision/pull/34, but I don't think there's a huge benefit of running those tests in parallel at the moment and the re-integration of subiquity_client makes this slightly more complicated again.

feat(ci): remove duplicate flutter-coverage job

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_init/lib/src/init_app.dart
packages/ubuntu_init/lib/src/init_services.dart
packages/ubuntu_provision/lib/services.dart
packages/ubuntu_provision/lib/src/services/theme_variant_service.dart
packages/ubuntu_provision/lib/src/services/theme_variant_service.freezed.dart
packages/ubuntu_provision/lib/src/services/theme_variant_service.g.dart
packages/ubuntu_provision/lib/theme_variant.dart
packages/ubuntu_provision/lib/ubuntu_provision.dart
packages/ubuntu_provision/pubspec.yaml
packages/ubuntu_provision/test/services/theme_variant_service_test.dart

Adds a `ThemeVariantService` to ubuntu-provision that loads some configuration options from the `ConfigService` and creates a `ThemeVariant`, which contains customized yaru themes and a window title.
Example configuration:
```yaml
bootstrap:
accent-color: '#0000ff'
elevated-button-color: '#ff0000'
elevated-button-text-color: '#00ff00'
window-title: 'My custom window title'
```
(the color parameters are already supported by yaru.dart without any further customization needed).
I'm sure we'll want to adjust details like config file location, scope, etc later on.
Ref #205
UDENG-1762

feat: add theme variant service

---

.github/workflows/ci.yml

Adds separate codecov flags for the Go backend and the Flutter UI so that we can track the coverage independently

feat(ci): use different codecov flags for UI and provd

---

snap/local/postinst.d/99_disable_user_creation

Overrides the default `users` config setting in the cloud-init config on the target system so that no default user is created.
Ref: #252
UDENG-1913

feat(snap): disable default user creation

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/lib/services/installer_service.dart
packages/ubuntu_bootstrap/test/services/installer_service_test.dart
packages/ubuntu_init/integration_test/ubuntu_init_test.dart
packages/ubuntu_init/lib/src/init_app.dart
packages/ubuntu_init/lib/src/init_model.dart
packages/ubuntu_init/lib/src/init_services.dart
packages/ubuntu_init/lib/src/init_wizard.dart
packages/ubuntu_init/test/init_model_test.dart
packages/ubuntu_init/test/init_model_test.mocks.dart
packages/ubuntu_provision/build.yaml
packages/ubuntu_provision/lib/services.dart
packages/ubuntu_provision/lib/src/services/page_config_service.dart
packages/ubuntu_provision/lib/src/services/page_config_service.freezed.dart
packages/ubuntu_provision/lib/src/services/page_config_service.g.dart
packages/ubuntu_provision/lib/src/services/theme_variant_service.dart
packages/ubuntu_provision/lib/src/services/theme_variant_service.freezed.dart
packages/ubuntu_provision/test/services/page_service_test.dart
packages/ubuntu_provision/test/services/theme_variant_service_test.dart
packages/ubuntu_provision/test/test_utils.dart
packages/ubuntu_provision/test/test_utils.mocks.dart

Follow-up to #239.
Adds a service that parses the 'pages' section of the configuration file following this schema:
```yaml
pages:
locale: false
keyboard:
image: '/path/to/image'
title: 'My custom window title'
```
This PR only replaces the previous 'pages' configuration that allowed passing a list of pages that should be included in the wizard. As before, by default all available pages are shown by default. What's changed is that the logic is now reversed: you need to exclude a page explicitly in the config file now. If a page is excluded but required by subiquity in autoinstall mode, a warning will be shown and only the pages by subiquity will be included. (We could also exit the wizard with an error, if that's preferred).
As a next step, I plan to add a provider that holds the parsed …

feat: add PageConfigService

---

snap/local/postinst.d/99_install_ubuntu_init

This postinstall script creates a script on the target system that fetches the ubuntu-desktop-init snap from a [test repo](https://github.com/d-loose/provision-testing) and installs it. Its execution is triggered by a systemd unit that runs after the network is initialized and snapd has finished seeding and before the display manager starts. Lastly, it overrides the `Exec=` line in `gnome-initial-setup.desktop`, making it point directly to the `ubuntu_init` binary from the snap (i.e. it runs outside any snap environment).
Ref: #252
UDENG-1913

feat: add script to install ubuntu init

---

packages/ubuntu_bootstrap/lib/services/refresh_service.dart
packages/ubuntu_init/lib/src/services/privacy_service.dart
packages/ubuntu_init/lib/src/services/xdg_identity_service.dart
packages/ubuntu_init/lib/src/services/xdg_keyboard_service.dart
packages/ubuntu_init/lib/src/services/xdg_locale_service.dart
packages/ubuntu_init/lib/src/services/xdg_session_service.dart
packages/ubuntu_init/lib/src/services/xdg_timezone_service.dart
packages/ubuntu_provision/lib/src/services/product_service.dart
packages/ubuntu_provision/lib/src/services/theme_service.dart

The debug error catching introduced in #258 got messed up in #272. This reverts those changes so that we can run the init wizard using those legacy services without crashing it.
I've added todo notes to the services that we'll need to deprecate and replace with calls to the provd daemon.

fix: catch all errors in init services

---

snap/local/postinst.d/99_install_ubuntu_init

Includes the latest init-snap in the postinst hook that sets up our testing pipeline and logs debug messages from the init wizard to `/tmp/init.log`

feat: update init snap in testing pipeline and log debug information

---

codecov.yaml
melos.yaml

* Removes generated protobuf files from coverage in `melos coverage:cleanup`
* Removes unneeded `ignore` rule in codecov.yaml
* Removes generated files from `melos format` for consistency

chore: remove generated files from coverage

---

packages/ubuntu_init/lib/src/init_wizard.dart

I noticed the images weren't correctly loading in the init wizard:

fix(init): load images from config file

---

snap/local/ubuntu-desktop-bootstrap.desktop
snap/snapcraft.yaml

This will require some changes to the iso at some point.
For testing, you can still inject the ubuntu-desktop-bootstrap snap into an iso, boot it, quit the installer and remove it, then launch ubuntu-desktop-bootstrap instead. A bit cumbersome, but we should be able to get those things onto the iso soon..

feat: rename ubuntu-desktop-installer snap to ubuntu-desktop-bootstrap

---

packages/ubuntu_init/lib/src/init_step.dart
packages/ubuntu_init/lib/src/init_wizard.dart

As some actions in the init wizard are done immediately and aren't trivially reversible, some of the wizard steps shouldn't allow the user to navigate back. I think the simplest solution is to explicitly set this as an individual property for each page in the wizard.
Close #305
UDENG-2061

feat(init): disable back buttons on certain pages

---

packages/ubuntu_init/integration_test/screenshot_test.dart
packages/ubuntu_init/integration_test/ubuntu_init_test.dart
packages/ubuntu_init/lib/src/init_app.dart
packages/ubuntu_init/lib/src/init_services.dart
packages/ubuntu_init/lib/src/init_step.dart
packages/ubuntu_init/lib/src/init_wizard.dart
packages/ubuntu_init/test/init_wizard_test.dart

Adds a `--welcome` argument to ubuntu_init that runs a separate desktop welcome wizard (stage 5 of the provisioning flow).
Close #204
UDENG-1760

feat(init): split off welcome wizard

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_provision/lib/src/services/desktop_service.dart
packages/ubuntu_provision/test/services/desktop_service_test.dart

* Don't register `DesktopService` in debug mode to not constantly mess up the developer's power settings
* Refactor `DesktopService` and catch/log all potential errors from non-existing dconf paths or DBus services so that flavors don't run into problems. We'll probably need to add additional `DesktopService` implementations at some point.
This should fix https://bugs.launchpad.net/ubuntustudio-system-installer/+bug/2049675.
I'd cherry-pick this into `archive/main`.
* Make sure the application ID in the Gnome Session `Inhibit()` call matches the one defined in CMakeLists.txt
Fix #338

feat: cleanup desktop service

---

packages/ubuntu_init/test/init_model_test.mocks.dart
packages/ubuntu_provision/lib/src/network/wifi_view.dart
packages/ubuntu_provision/test/network/test_network.dart

If there is only one wifi network adapter, its name should not show, only the access points.
This PR also adds a loading indicator to the wifi that it is connecting to, so that it isn't only shown on the adapter (which now wouldn't be seen).
Closes #358

fix: Only show wifi device if there are more devices

---

packages/ubuntu_bootstrap/integration_test/screenshot_test.dart
packages/ubuntu_bootstrap/integration_test/ubuntu_bootstrap_test.dart
packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/lib/installer/installation_step.dart
packages/ubuntu_bootstrap/lib/services.dart
packages/ubuntu_bootstrap/lib/services/active_directory_service.dart
packages/ubuntu_bootstrap/lib/services/identity_service.dart
packages/ubuntu_bootstrap/lib/services/installer_service.dart
packages/ubuntu_bootstrap/lib/services/timezone_service.dart
packages/ubuntu_bootstrap/test/installer_wizard_test.dart
packages/ubuntu_bootstrap/test/services/active_directory_service_test.dart
packages/ubuntu_bootstrap/test/services/identity_service_test.dart
packages/ubuntu_bootstrap/test/services/timezone_service_test.dart
packages/ubuntu_init/integration_test/ubuntu_init_test.dart
packages/ubuntu_provision/lib/src/active_directory/active_directory_page.dart
packages/ubuntu_provision_test/lib/src/expect.dart
packages/ubuntu_provision_test/lib/src/fake_init.dart

Adds the identity, active directory and timezone pages back into ubuntu bootstrap (they're now shown immediately before the confirmation page). I've removed the `FakeSystemService` we used in ubuntu init to test user creation and restored the original behavior of `expectIdentity`.
We'll need to remove the [postinst script](https://github.com/canonical/ubuntu-desktop-provision/blob/44dff1bea18dcc384d7f7d268946773ccd480e19/snap/local/postinst.d/99_disable_user_creation) that disables user creation from the snap and then find a solution for the OEM case where the identity page will be hidden and no user account should be created. I'll open separate issues for those things after merging this.
Looks like this now:
[Screencast from 2024-01-31 …

feat: reintegrate identity, active directory and timezone pages into ubuntu bootstrap

---

snap/local/postinst.d/99_disable_user_creation

Follow up to #370. To re-enable user account creation in ubuntu bootstrap, this script needs to be removed. We might need to re-add it later in a slightly modified way to support the OEM case.

feat: remove 99_disable_user_creation postinst script

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_init/lib/src/init_services.dart
packages/ubuntu_provision/lib/src/services/config_service.dart
packages/ubuntu_provision/test/services/config_service_test.dart
packages/ubuntu_provision/test/test_utils.mocks.dart

Now only looks for the config file in `/usr/share/desktop-provision/whitelabel.{yaml,yml}` and no longer takes in a custom config file as a command line argument.

feat: Simplify directory paths for whitelabel config file

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/lib/services/installer_service.dart
packages/ubuntu_bootstrap/test/services/installer_service_test.dart
packages/ubuntu_bootstrap/test/test_utils.mocks.dart
packages/ubuntu_init/test/init_model_test.mocks.dart
packages/ubuntu_provision/lib/src/services/page_config_service.dart
packages/ubuntu_provision/test/services/page_config_service_test.dart
packages/ubuntu_provision/test/test_utils.mocks.dart

When the user sets `oem: true` in the config file the `eula` page should be forced and the `identity` page should be removed from stage 3, if subiquity responds with interactive pages this behavior has no effect.

feat: When oem is true in installer, force eula and remove identity

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_init/lib/src/init_app.dart
packages/ubuntu_provision/lib/src/services/theme_variant_service.dart
packages/ubuntu_provision/lib/src/services/theme_variant_service.freezed.dart
packages/ubuntu_provision/lib/src/services/theme_variant_service.g.dart
packages/ubuntu_provision/test/services/theme_variant_service_test.dart

Replaces `window-title` from `theme` scope with `app-name` in top-level scope.

feat(whitelabel): read app title from top-level config scope

---

packages/ubuntu_bootstrap/test/test_utils.dart

Although it doesn't cause a failure, the tests are [complaining](https://github.com/canonical/ubuntu-desktop-provision/actions/runs/7848565423/job/21419979742#step:7:172) about a missing stub.

fix(bootstrap): add isOem to page config mock

---

.github/ISSUE_TEMPLATE/new-task.md

Adds an issue template that reminds users to use the launchpad issue tracker for bug reports as mentioned in the readme.

feat: add issue template

---

melos.yaml
packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/lib/pages/install/install_page.dart
packages/ubuntu_bootstrap/lib/pages/loading/loading_page.dart
packages/ubuntu_bootstrap/lib/pages/rst/rst_page.dart
packages/ubuntu_bootstrap/lib/pages/source/not_enough_disk_space/not_enough_disk_space_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/bitlocker/bitlocker_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/guided_reformat/guided_reformat_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/security_key/security_key_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/storage_dialogs.dart
packages/ubuntu_bootstrap/lib/pages/storage/storage_page.dart
packages/ubuntu_bootstrap/lib/pages/try_or_install/try_or_install_page.dart
packages/ubuntu_bootstrap/lib/slides/default_slides.dart
packages/ubuntu_bootstrap/pubspec.yaml
packages/ubuntu_init/lib/src/init_app.dart
packages/ubuntu_init/lib/src/telemetry/telemetry_page.dart
packages/ubuntu_init/pubspec.yaml
packages/ubuntu_provision/lib/src/accessibility/accessibility_page.dart
packages/ubuntu_provision/lib/src/locale/locale_page.dart
packages/ubuntu_provision/lib/src/providers/flavor.dart
packages/ubuntu_provision/pubspec.yaml
packages/ubuntu_provision/test/providers/flavor_test.dart
packages/ubuntu_provision_test/lib/src/provision_tester.dart
packages/ubuntu_provision_test/pubspec.yaml
packages/ubuntu_wizard/pubspec.yaml

Parses the `flavor` from the config file. If it can't be parsed (i.e. it's not one of budgie, cinnamon, edubuntu, kubuntu, kylin, lubuntu, mate, studio, ubuntu, unity or xubuntu) it uses [`ubuntu_flavor`](https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_flavor)'s `detect()`, which tries to determine the flavor from the value of `XDG_CURRENT_DESKTOP`. 'ubuntu' is used as a fallback.
The flavor determines the primary color of the yaru theme as well as the `DISTRO` name used in l10n strings.
Closes #415
UDENG-2300

feat: read flavor from config

---

packages/ubuntu_init/assets/kbds
packages/ubuntu_init/pubspec.yaml

The keyboard files imported from subiquity are no longer needed in the UI after merging #381

feat(init): remove obsolete keyboard assets

---

provd/internal/testutils/systembus.go

I had a problem in my machine when copying these testutils. I hit
> system bus mock is not running. If that's intended, manually connect to the system bus instead of using this function
after calling both 
```
StartLocalSystemBus()
GetSystemBusConnection()
```
Turned out my system would create a unix:path instead of a unix:abstract socket.
Either of them existing means that the private Dbus is running and so I propose checking for both.

fix(provd): bus is up if unix:path exists

---

packages/ubuntu_provision/lib/src/providers/flavor.dart
packages/ubuntu_provision/test/providers/flavor_test.dart
packages/ubuntu_provision_test/lib/src/provision_tester.dart

In order to avoid any confusion, we've decided to simplify the configuration for flavors. This PR removes the automatic detection mechanism based on `XDG_CURRENT_DESKTOP`, so that the flavor needs to be set explicitly via the `flavor` key in `/usr/share/desktop-provision/whitelabel.yaml`.

feat: remove flavor detection

---

packages/ubuntu_init/lib/src/init_model.dart

Until we have a gdm service in provd, let's make sure we handle errors while trying to launch the desktop session gracefully.

feat(init): catch and log errors when lauching gdm session

---

packages/ubuntu_provision/lib/src/services/sound_service.dart

This is a quick workaround so that we don't crash on systems without `canberra-gtk-play`, until #419 is done.

fix: Don't crash if `canberra-gtk-play` doesn't exist

---

.github/renovate.json

The subiquity submodule is out of date again and renovate doesn't seem to open update PRs for it. I suspect it's because that feature is still in beta testing and needs to be enabled [explicitly](https://docs.renovatebot.com/modules/manager/git-submodules/).

fix(renovate): enable git submodules

---

.github/workflows/ci.yml
packages/ubuntu_init/integration_test/e2e_test.dart
provd/example.config.yaml

Current CI setup:
* Manually run `provd` as `root`
* Allow everyone `rw` access to `/run/provd/provd.sock`
An issue with that setup is, that `provd` can't change any gsettings options:
```
(process:16409): dconf-WARNING **: 10:58:40.715: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY
```
I've left todo notes to add tests for the privacy service and the gnome keyboard input sources that rely on those, once we have a solution.
Once we figure the details on how to run `provd` as the `gnome-initial-setup` and use systemd socket activation, we should do that in the e2e test as well.
For reference, here's what I've tried so far (using the systemd files from #241):
```yaml
...
- name: Setup polkit rules
run: |
sed "s/gnome-initial-setup/$USER/g" …
```

test: add end-to-end test for ubuntu-init + provd

---

snap/bootstrap/snapcraft.yaml

This package seems to be required by subiquity now, see https://github.com/canonical/subiquity/pull/1910.

feat(bootstrap): stage python3-distro-info in snapcraft

---

packages/ubuntu_init/lib/src/init_wizard.dart

Reverts a small change from #451. `onLoad` is never called on the first route in the wizard, so we need to rely on `onReplace` to initialize the model and precache the images

fix(init): ensure init model is initialized

---

ci/snap/bootstrap/snapcraft.yaml

Without explicitly specifying the `source-type` I keep running into build issues when running `snapcraft` locally, because the subiquity submodule doesn't get initialized.

fix(snapcraft): restore `source-type: git`

---

ci/snap/init/snapcraft.yaml
packages/ubuntu_init/lib/src/init_app.dart
packages/ubuntu_init/pubspec.yaml

Removes the outdated plugs and replaces them with:
- `network` and `network-manager` to access the network and configure network-manager
- `system-files`-based plugs that allow access to various locations in the host file system:
- `/usr/share/desktop-provision` (r) - configuration directory for whitelabelling
- `/run/provd/provd.sock` (rw) - communication with provd
- `/var/log/installer` (w) - logging
What's left to figure out is how to access GDM via DBus. There's no interface that lets us do this using the current dart implementation of the GDM service in ubuntu-init. #455 adds that capability to provd, but we need to figure out how provd can access GDM if it runs as a socket-activated systemd service.

feat(init): update snap interfaces

---

.github/workflows/rebase-for-snap-cicd.yaml

After running `git reset --hard main` we need to update the submodule, otherwise the previous state of the submodule will be included in the top commit (see [here](https://github.com/canonical/ubuntu-desktop-provision/commit/f92f8d9057082d5f6864c53a64d21178a7420b68)).
This should fix https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2055225 which was caused by a mismatch between subiquity versions.

fix(ci): update submodules after git reset

---

ci/snap/init/snapcraft.yaml
packages/ubuntu_init/lib/src/services/gdm_service.dart

Until we have sorted out the permission issues for #455, we need to rely on the existing dart implementation of the GDM service to launch the desktop session. Since GDM exposes its private socket in the host's `/tmp/` directory, we need yet another `system-files` plug to access that.

fix(init): patch /tmp/ path for gdm service in snap

---

.tool-versions
melos.yaml
packages/provd_client/pubspec.yaml
packages/subiquity_client/pubspec.yaml
packages/subiquity_test/pubspec.yaml
packages/ubuntu_bootstrap/lib/pages/storage/guided_resize/storage_size_dialog.dart
packages/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_dialogs.dart
packages/ubuntu_bootstrap/lib/pages/storage/storage_dialogs.dart
packages/ubuntu_bootstrap/pubspec.yaml
packages/ubuntu_bootstrap/test/storage/guided_resize/storage_size_dialog_test.dart
packages/ubuntu_init/pubspec.yaml
packages/ubuntu_provision/lib/src/keyboard/keyboard_widgets.dart
packages/ubuntu_provision/pubspec.yaml
packages/ubuntu_provision/test/test_utils.mocks.dart
packages/ubuntu_provision_test/pubspec.yaml
packages/ubuntu_utils/pubspec.yaml
packages/ubuntu_wizard/pubspec.yaml

The biggest change is that we had to migrate to use the `HardwareKeyboard` API.
https://docs.flutter.dev/release/breaking-changes/key-event-migration
Autofocus is removed from the spinbox, since it throws assertions when the number goes down, not a big loss UX-wise.

chore: Update to Flutter 3.19.2

---

packages/ubuntu_provision/lib/src/network/ethernet_view.dart
packages/ubuntu_provision/lib/src/network/wifi_view.dart
packages/ubuntu_provision/test/network/ethernet_view_test.dart
packages/ubuntu_provision/test/network/wifi_view_test.dart

fix: Disable network radio buttons instead of showing a red cross

---

packages/ubuntu_provision/test/keyboard/keyboard_page_test.dart

@spydon the keyboard page still looks fine to me on small layouts, although a bit more scrolling is required. Feel free to propose a better solution tomorrow, if you have one :)

fix(keyboard_page_test): scroll to item before tapping it

---

provd/go.mod

Bump the go tool-chain to 1.22.1 to get past security vulns
This also gives me some neat fixes I want to use in my tests :slightly_smiling_face:

chore(provd): bump go toolchain to 1.22.1

---

.github/workflows/ci.yml
ci/snap/init/snapcraft.yaml
packages/ubuntu_init/lib/src/services/provd_address.dart
provd/example.config.yaml
provd/internal/consts/consts.go

This aligns the snap with the socket path that will be used for the init backend moving forward
I had to move it into `/run/gnome-initial-setup` as the gis user has ownership only over that `/run` subdirectory

feat(snap): update provd socket paths

---

packages/ubuntu_bootstrap/integration_test/ubuntu_bootstrap_test.dart
packages/ubuntu_bootstrap/lib/services/installer_service.dart
packages/ubuntu_provision/lib/src/services/page_config_service.dart

See https://github.com/canonical/subiquity/pull/1928
Close #376
UDENG-2226

feat(bootstrap): skip user creation and timezone for OEM

---

packages/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart
packages/ubuntu_bootstrap/lib/pages/loading/loading_page.dart
packages/ubuntu_bootstrap/lib/pages/refresh/refresh_widgets.dart
packages/ubuntu_bootstrap/lib/pages/rst/rst_page.dart
packages/ubuntu_bootstrap/lib/pages/secure_boot/secure_boot_page.dart
packages/ubuntu_bootstrap/lib/pages/source/not_enough_disk_space/not_enough_disk_space_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/bitlocker/bitlocker_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/guided_reformat/guided_reformat_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/guided_resize/guided_resize_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/passphrase/passphrase_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/recovery_key/recovery_key_page.dart
packages/ubuntu_bootstrap/lib/pages/try_or_install/try_or_install_page.dart
packages/ubuntu_bootstrap/test/refresh/refresh_page_test.dart
packages/ubuntu_bootstrap/test/source/not_enough_disk_space_test.dart
packages/ubuntu_init/lib/src/privacy/privacy_page.dart
packages/ubuntu_init/lib/src/telemetry/telemetry_page.dart
packages/ubuntu_init/lib/src/ubuntu_pro/ubuntu_pro_page.dart
packages/ubuntu_provision/lib/src/accessibility/accessibility_page.dart
packages/ubuntu_provision/lib/src/active_directory/active_directory_page.dart
packages/ubuntu_provision/lib/src/identity/identity_page.dart
packages/ubuntu_provision/lib/src/network/network_page.dart
packages/ubuntu_provision/lib/src/timezone/timezone_page.dart
packages/ubuntu_provision/lib/src/widgets/horizontal_page.dart
packages/ubuntu_wizard/lib/src/wizard_button.dart
packages/ubuntu_wizard/test/nested_wizard_test.dart
packages/ubuntu_wizard/test/wizard_page_test.dart

And the label is now "Back" instead of "Previous".

fix: Rename `PreviousWizardButton` to `BackWizardButton`

---

README.md

I'll delete `bootstrap-snap` and `init-snap` as they're obsolete now.

docs: update snap branches in README

---

packages/ubuntu_bootstrap/lib/pages/storage/storage_model.dart
packages/ubuntu_bootstrap/test/storage/storage_model_test.dart
packages/ubuntu_bootstrap/test/storage/test_storage.mocks.dart

Core desktop is installed by copying a disk image directly to the hard disk, so other options like partitioning or installing along the current operating systems aren't supported.
This patch removes all those options when installing core desktop.

In core desktop only allow to erase the disk

---

melos.yaml

An attempt to resolve the recent dependency issues that are causing [test failures](https://github.com/canonical/ubuntu-desktop-provision/actions/runs/8295061463/job/22701953088)

ci(melos): don't run pub get in parallel

---

packages/ubuntu_bootstrap/lib/pages/try_or_install/try_or_install_model.dart
packages/ubuntu_bootstrap/lib/pages/try_or_install/try_or_install_page.dart
packages/ubuntu_bootstrap/test/installer_wizard_test.dart
packages/ubuntu_bootstrap/test/try_or_install/test_try_or_install.dart
packages/ubuntu_bootstrap/test/try_or_install/test_try_or_install.mocks.dart
packages/ubuntu_bootstrap/test/try_or_install/try_or_install_model_test.dart
packages/ubuntu_bootstrap/test/try_or_install/try_or_install_page_test.dart

This also removes the unused `none` and `repairUbuntu` options and makes `installUbuntu` the default.
Ref: #495 
UDENG-2506

feat(bootstrap): show 'close' button when selecting 'try'

---

packages/ubuntu_provision/lib/src/providers/page_images.dart
packages/ubuntu_provision/test/providers/page_images_test.dart

It was reported from the flavor folks that SVGs couldn't be loaded from the filesystem anymore, this fixes that and makes the test a bit more reliable.

fix: PageImages should be able to load SVGs from file

---

packages/ubuntu_bootstrap/lib/pages/loading/loading_page.dart
packages/ubuntu_provision/lib/src/locale/locale_page.dart

Removes the 'back' button from the locale page, which is the first interactive page in both bootstrap and init. Also removes the unnecessary buttons from the loading page.

feat: remove button(s) from locale and loading page

---

packages/ubuntu_bootstrap/lib/pages/storage/storage_page.dart

Sorry, missed that one. With the boxes removed we don't need any additional spacers.
Ref: #495
UDENG-2506

fix(bootstrap): remove horizontal spacer on storage page

---

packages/ubuntu_bootstrap/integration_test/ubuntu_bootstrap_test.dart
packages/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_dialogs.dart
packages/ubuntu_bootstrap/test/storage/manual/manual_storage_dialogs_test.dart
packages/ubuntu_bootstrap/test/widgets/storage_size_box_test.dart
packages/ubuntu_utils/lib/src/data_size.dart
packages/ubuntu_utils/test/data_size_test.dart

This fixes a data size unit inconsistency:
[`toBytes` and `fromBytes`](https://github.com/canonical/ubuntu-desktop-provision/blob/d2dcc733537bfcc84bc9470ed69bd7defa1dec85/packages/ubuntu_utils/lib/src/data_size.dart#L27-L33) from `ubuntu_utils` are using base-2, but are always used in conjunction with [`formatByteSize`](https://github.com/canonical/ubuntu-flutter-plugins/blob/a219aca346fbd732b9ef4d2958dd83ccb70e5883/packages/ubuntu_localizations/lib/src/data_size.dart#L39-L53) from `ubuntu_localizations`, which uses base-10.
Base-10 is correct here as the corresponding [l10n strings](https://github.com/canonical/ubuntu-flutter-plugins/blob/a219aca346fbd732b9ef4d2958dd83ccb70e5883/packages/ubuntu_localizations/lib/src/l10n/ubuntu_en.arb#L235-L246) use SI prefixes. See also …

fix(ubuntu_utils): use base 1000 for SI units

---

packages/ubuntu_provision/lib/src/network/network_page.dart
packages/ubuntu_provision/lib/src/network/wifi_view.dart
packages/ubuntu_provision/lib/src/widgets/horizontal_page.dart

fix: Correct padding and divider for the network page

---

packages/ubuntu_bootstrap/lib/pages/source/codecs_and_drivers_page.dart
packages/ubuntu_provision/lib/src/accessibility/accessibility_page.dart
packages/ubuntu_provision/lib/src/identity/identity_page.dart
packages/ubuntu_provision/lib/src/network/network_page.dart
packages/ubuntu_provision/lib/src/widgets/horizontal_page.dart

The content flex is only needed if `managedScrolling` is false.

fix: Remove unnecessary content flex

---

packages/ubuntu_bootstrap/lib/installer.dart

When running the installer in live mode the following message is written to the logs:
```
flutter: WARNING subiquity_server: Unable to find the subiquity_client package. Falling back to the current working dir: /home/ubuntu
```
This happens because `getSubiquityPath()` is called even if the installer doesn't spawn its own subiquity server. Removing the local variable should solve this and make the logs a little less confusing for people trying to debug issues :)

fix(bootstrap): don't search for subiquity in live run

---

README.md
packages/ubuntu_bootstrap/lib/pages/install/done_page.dart

Some long distribution titles overflowed apparently,

fix: More title space on the done page

---

packages/ubuntu_provision/lib/src/identity/identity_model.dart
packages/ubuntu_provision/test/identity/identity_model_test.dart

fix: realName on identity page can’t be empty.

---

.gitignore
packages/factory_reset_tools/.gitignore
packages/factory_reset_tools/.metadata
packages/factory_reset_tools/README.md
packages/factory_reset_tools/analysis_options.yaml
packages/factory_reset_tools/data/factory-reset-tools-object.xml
packages/factory_reset_tools/lib/cmdline.dart
packages/factory_reset_tools/lib/dbus_daemon.dart
packages/factory_reset_tools/lib/dbus_local_object.dart
packages/factory_reset_tools/lib/dbus_remote_object.dart
packages/factory_reset_tools/lib/main.dart
packages/factory_reset_tools/lib/pages/home.dart
packages/factory_reset_tools/lib/pages/reboot.dart
packages/factory_reset_tools/lib/pages/reset_media.dart
packages/factory_reset_tools/lib/reboot.dart
packages/factory_reset_tools/lib/reset_media.dart
packages/factory_reset_tools/linux/.gitignore
packages/factory_reset_tools/linux/CMakeLists.txt
packages/factory_reset_tools/linux/flutter/CMakeLists.txt
packages/factory_reset_tools/linux/main.cc
packages/factory_reset_tools/linux/my_application.cc
packages/factory_reset_tools/linux/my_application.h
packages/factory_reset_tools/pubspec.yaml

This moves over the [factory_reset_tools](https://github.com/canonical/factory-reset-tools) project to the monorepo and makes it adhere to the standards set for the monorepo.
A branch also needs to be created for the snap directory.

feat: Transfer factory_reset_tools to monorepo

---

packages/ubuntu_bootstrap/lib/pages/storage/guided_reformat/guided_reformat_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/guided_resize/guided_resize_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/passphrase/passphrase_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/storage_page.dart
packages/ubuntu_bootstrap/test/storage/storage_page_test.dart
packages/ubuntu_bootstrap/test/test_utils.dart
packages/ubuntu_provision/lib/src/network/network_page.dart
packages/ubuntu_provision/lib/src/widgets/horizontal_page.dart
packages/ubuntu_wizard/lib/src/wizard_button.dart

This ensures that the storage model is reset if the user decides to go back in the flow and select a different option.
I've tried to clarify the meaning of `NextWizardButton`'s `onReturn` parameter (which was previously called `onExecute` and `onBack` before that). We should definitely spend some time on refactoring `ubuntu_wizard` in the future, since some of the mechanisms involved are quite tricky and hard to understand.
Another issue is that there are multiple ways of modifying the behavior of the buttons in the bottom bar of the new `HorizontalPage`: either by overriding the entire `bottomBar` or by passing arguments such as `isNextEnabled` that modify the *default* bar. I've added an assertion to assure that those parameters aren't specified at the same time. I'd rather remove one …

fix(bootstrap): reset storage model when navigating back

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/lib/pages/loading/loading_page.dart

This moves the futures that wait for the connection to subiquity and initialize the services into a future builder wrapping the `InstallerWizard`, so that we can show the loading page early on, avoiding common 'blank window' issues like https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2056160/.

feat(bootstrap): show loading page while waiting for subiquity

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/lib/installer/installer_model.dart
packages/ubuntu_bootstrap/test/installer_model_test.dart

This is a follow-up to #589, also concerning the delay during subiquity's startup.
As Olivier pointed out [here](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2056160/comments/9), we're currently checking for snap updates before launching the installer wizard. If there's no network connection at this point, the blocking call takes 30 seconds to time out.
I think the simplest solution is to remove that call from there entirely, as it is done [later on](https://github.com/canonical/ubuntu-desktop-provision/blob/c7967e539a90ddad181dbdb1456fd51cb092fa44/packages/ubuntu_bootstrap/lib/pages/refresh/refresh_model.dart#L24) anyways.
~~Even though the refresh page is shown after the network page, the user could still choose not to connect to the internet, so I added a connectivity check …

feat(bootstrap): don't check for updates in `_initInstallerApp`

---

CONTRIBUTING.md
README.md

Due to weblate's quirks there are a bunch of different components linked to this repository. Is it enough to just link to the ubuntu-desktop-translations project?

docs: add link to weblate

---

packages/ubuntu_bootstrap/lib/pages/autoinstall/autoinstall_page.dart

fix: Move validate button to next button placement

---

.github/workflows/ci.yml
provd/debian/changelog
provd/internal/services/user/password_hash.go

All the non-amd64 builds are failing on LP from the following error:
```
/usr/include/glib-2.0/glib/gtypes.h:34:10: fatal error: glibconfig.h: No such file or directory
34 | #include <glibconfig.h>
|          ^~~~~~~~~~~~~~
```
I've added a pkg-config line to fix this in all archs
packaging building on all on lp:
https://launchpad.net/~matt-hagemann/+archive/ubuntu/provd/+packages
closes #599

C include path fix

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/lib/installer/installer_wizard.dart

The generic error page currently relies on subiquity to restart the machine. Depending on the cause of the installation failure, subiquity might not be able to receive requests anymore, though. Let's show a 'close' button instead, and let the user take care of a reboot themselves, if they decide to follow the hint shown on the page.
https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2060749

feat(bootstrap): don't reboot after failed installation

---

provd/debian/control
provd/debian/rules

Tried using sbuild to build provd, found it is using home directory as cache which sbuild does not allow.
I followed patch similar to https://bugs.launchpad.net/ubuntu/+source/calamares-settings-ubuntu/+bug/2060151 so that GOCACHE and GOMODCACHE does not use home directory.
Also, ca-certificates is not part of sbuild chroot, so it is added to Build-Depends as well.

provd: resolve build issues when using sbuild

---

.github/workflows/pr.yaml

While issues with the CLA check are still being sorted out, let's skip it in the PR workflow.

ci: temporarily skip CLA check

---

provd/debian/changelog
provd/debian/provd.postinst
provd/debian/provd.postrm
provd/sprovd/sprovd.go

Move away from using gnome-initial-setup group, which is owned and created by gnome-initial-setup, and make use of a provd group, including all its lifecycle management.

fix(provd): use provd group, not gnome-initial-setup group

---

packages/ubuntu_bootstrap/lib/services/keyboard_service.dart
packages/ubuntu_bootstrap/test/installer_wizard_test.dart
packages/ubuntu_bootstrap/test/services/keyboard_service_test.dart

Follow-up to #627 
Fixes https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2058503 by additionally invoking `setxkbmap`. It introduces a tiny amount of lag after selecting the keyboard layout, as the UI waits for the command to return. We could instead mark this as `unawaited`, since it's unlikely that the user manages to type in the test field before the command returns - any thoughts?
I've checked that this works on the latest Xubuntu image and that it doesn't do any harm on Ubuntu (besides the small lag).

feat(bootstrap): set keyboard via setxkbmap

---

packages/subiquity_client/lib/src/types.dart
packages/subiquity_client/lib/src/types.freezed.dart
packages/subiquity_client/lib/src/types.g.dart
packages/subiquity_client/test/status_monitor_test.dart
packages/subiquity_client/test/types_test.dart
packages/subiquity_test/lib/src/fakes.dart
packages/ubuntu_bootstrap/test/install/install_model_test.dart
packages/ubuntu_bootstrap/test/installer_test.dart
packages/ubuntu_bootstrap/test/services/storage_service_test.dart

Regenerates `subiquity_client`'s types to include the `nonReportableError` field in subiquity's `ApplicationStatus` introduced in https://github.com/canonical/subiquity/pull/1925.

feat(bootstrap): add support for non reportable errors from subiquity

---

CONTRIBUTING.md

Since we mention the contribution guidelines in the github issue template that is supposed to direct users to the launchpad issue tracker, let's add a link there as well.

docs: add bugtracker link to CONTRIBUTING.md

---

packages/ubuntu_bootstrap/lib/installer/installation_step.dart
packages/ubuntu_bootstrap/lib/installer/installer_wizard.dart
packages/ubuntu_bootstrap/lib/services/installer_service.dart
packages/ubuntu_bootstrap/test/installer_wizard_test.dart
packages/ubuntu_bootstrap/test/services/installer_service_test.dart

This simplifies the page setup logic:
* Get list of interactive sections from subiquity and map them to pages in the installer. If the result isn't empty, populate the wizard with those pages and ignore any `visible: false` from the config.
* If subiquity didn't provide any interactive sections, show all pages provided in the whitelabel.yaml, respecting `visible: false`.
I've also added a `required` property to the `InstallationStep` to simplify the logic in the wizard's `predicate` and keep everything in one place. Required pages are `loading`, `error`, `confirm`, `install` (for obvious reasons) and also `rst` and `secureBoot`, which weren't included before.
Fixes [autoinstall: interactive-sections: "*" causes the UI to hang](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/206086 …

fix(bootstrap): map subiquity sections to pages in autoinstall

---

packages/factory_reset_tools/lib/horizontal_page.dart
packages/ubuntu_bootstrap/lib/pages/storage/storage_page.dart
packages/ubuntu_provision/lib/src/widgets/horizontal_page.dart
packages/ubuntu_wizard/lib/src/wizard_button.dart

We don't use this feature anywhere and it is quite dirty to pass around untyped data, so better restrict the possibility to use it.
I found this while trying to work out a solution for pressing enter to go to the next page.

fix: Remove untyped "next"-arguments

---

ci/snap/bootstrap/local/postinst.d/10_configure_auto_login
packages/ubuntu_bootstrap/lib/installer.dart

#651 didn't fix the [broken autologin](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2037592) as I had hoped. Turns out the respective postinst script was reading data from `/tmp/ubuntu_desktop_installer.conf`, while we're now writing to `/tmp/ubuntu_bootstrap.conf`. To avoid future confusion I've hardcoded the file name now instead of determining it from the executable.

fix(bootstrap): fix temporary postinstall config path

---

provd/internal/daemon/daemon_test.go

closes #610 
These time increases seemed to help solve the problem on the runners :crossed_fingers:

Fix: flaky TestQuit on arm

---

ci/snap/reset-tools/snapcraft.yaml

The last PR has some bugs in building snapcraft.yaml, as I forgot to remove lines that copy desktop entry (`factory-reset-tools.desktop`) and icon (`factory-reset-tools.png`), since it is now using default path (snap/gui) for both of these files.
Also, according to a comment in manual review (https://forum.snapcraft.io/t/manual-review-autoconnect-request-for-factory-reset-tools/39404/7), I am asked to change a name of system-files interface in order to fit the convention.

reset-tools: fixes and improvements in snapcraft.yaml

---

ci/snap/reset-tools/snapcraft.yaml

The script in the image that runs after dumping the installer into the reset media uses `uuidgen` to generate a new UUID in order for casper to mount onto the correct partition.
This commit adds missing uuid-runtime dependency.

fix(reset-tools): add uuid-runtime in snapcraft.yaml

---

melos.yaml
packages/ubuntu_bootstrap/pubspec.yaml
packages/ubuntu_init/pubspec.yaml
packages/ubuntu_provision/lib/src/interfaces/provisioning_page.dart
packages/ubuntu_provision/lib/src/keyboard/keyboard_page.dart
packages/ubuntu_provision/lib/src/locale/locale_page.dart
packages/ubuntu_provision/lib/src/network/network_page.dart
packages/ubuntu_provision/lib/src/network/wifi_view.dart
packages/ubuntu_provision/pubspec.yaml
packages/ubuntu_wizard/pubspec.yaml

This also refactors the wifi page to use providers groups instead of the static providers that it was overriding through the providerscope previously.

fix: Add possiblity to tab out of list on wifi page

---

packages/subiquity_client/lib/src/status_monitor.dart

While looking into [this bug](https://bugs.launchpad.net/subiquity/+bug/2063124) I noticed that we're not logging any errors when fetching subiquity's status fails.

feat(subiquity_client): log errors in status monitor

---

packages/factory_reset_tools/lib/pages/creation_progress_page.dart

This uses actual `createResetMedia` to run the media creation

fix(reset-tools): really create reset media in the UI

---

ci/snap/bootstrap/local/launcher

udisks2-inhibit is being moved in the live environment to a service. Interact with that instead, instead of hardcoding the rules.
Depends on https://code.launchpad.net/~dbungert/livecd-rootfs/+git/livecd-rootfs/+merge/464842 is merged.
LP: #2063192

fix(bootstrap): use udisks2-inhibit.service

---

packages/factory_reset_tools/lib/dbus/cmdline.dart

When running `factory-reset-tools.cli reboot`, it shows the messages below:
```
List of available options:
ResetOptionType.factoryReset: Restore Ubuntu to factory state
This option will restore Ubuntu to factory default, removing all files stored in this system during the process.
ResetOptionType.fwSetup: UEFI Firmware Settings
Restart into UEFI Firmware (BIOS) Settings menu.
```
Of which `ResetOptionType.factoryReset` is the enum string, and this should be the enum value `factory-reset` so when entering `factory-reset-tools.cli reboot factory-reset` it should start the reset.

fix(reset-tools): fix listing options in reboot in cli

---

packages/ubuntu_init/lib/src/init_step.dart

This makes it possible to hide the EULA page from the stage 4 init wizard via
```yaml
pages:
eula:
visible: false
```
Even though we don't parse the `mode` setting in stage 4 yet, OEMs should set
```yaml
mode: oem
```
in the config as well. In the future this will determine which pages are shown by default and affect the copy on some pages.

feat(init): make EULA page hidable

---

ci/snap/init/snapcraft.yaml

This was mistakenly removed in #462. Turns out it was not only needed for the (now moved to provd) sysmetrics package, but also for the auto generation of the hostname. See https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2064092.
In the interest of time I suggest re-introducing the plug for now. We should consider handling this via an endpoint in provd as well, though.

fix(init): restore hardware-observe plug

---

provd/cmd/provd/daemon/daemon.go
provd/cmd/provd/daemon/daemon_test.go
provd/cmd/provd/daemon/export_test.go
provd/cmd/provd/daemon/keyring.go

This runs `gnome-keyring-daemon --unlock` with a temporary password before launching the provd daemon, so that network manager doesn't complain about missing agents. By default the network credentials will be stored in `/etc/netplan` instead of the user's keyring, though. To fix [lp:2063313](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2063313) we don't need to worry about copying the keyring to the new user's directory and updating the password. I'd open a separate issue for that. 
Fix #711

fix(provd): unlock login keyring on startup

---

packages/ubuntu_provision_test/lib/src/provision_tester.dart

This is an attempt to fix the constant regeneration of screenshots for the identity page (see e.g. https://github.com/canonical/ubuntu-desktop-provision-screenshots/pull/297), due to non-deterministic behavior.

fix(screenshot_test): finish text editing on identity page

---

ci/snap/bootstrap/snapcraft.yaml

When running `ubuntu-bug ubuntu-desktop-bootstrap` the following error is shown:
I suspect we need to add the corresponding URL to the snapcraft.yaml
Will make the link on the error page invoke `ubuntu-bug` in a separate PR, once this works :)

chore(bootstrap): add bugtracker url to snapcraft.yaml

---

ci/snap/bootstrap/snapcraft.yaml

The change to add 'contact' doesn't to be enable ubuntu-bug to work, checking what was done for ubuntu-desktop-installer previous cycle 'issues' should also be set (described in https://snapcraft.io/docs/snapcraft-yaml-reference)

chore(bootstrap): define the issues url in snapcraft.yaml

---

packages/ubuntu_wizard/pubspec.yaml

I suspect this override got included by accident. It's causing [test failures](https://github.com/canonical/ubuntu-desktop-provision/actions/runs/9225981469/job/25384741300) now due to the recently updated yaru libs.

fix(ubuntu_wizard): remove yaru override

---

provd/go.mod

Fixes the vulnerability causing the ci to fail by bumping the version of the go toolchain that is used to build provd.

chore(provd): go toolchain bump 1.22.3

---

melos.yaml
packages/ubuntu_bootstrap/pubspec.lock
packages/ubuntu_bootstrap/pubspec.yaml
packages/ubuntu_init/pubspec.lock
packages/ubuntu_init/pubspec.yaml
packages/ubuntu_provision/pubspec.yaml
packages/ubuntu_wizard/pubspec.yaml

Upgrading `ubuntu_widgets` seems to resolve the RTL issue in `ListWidget`:
|Before|After|
|-|-|
|![Screenshot from 2024-05-08 16-33-25](https://github.com/canonical/ubuntu-desktop-provision/assets/113362648/81e2209b-fa0e-4918-b09d-fe32e1b1a8f7)|![Screenshot from 2024-05-08 16-31-35](https://github.com/canonical/ubuntu-desktop-provision/assets/113362648/cc6b31d8-284d-4632-92ea-737e20f141bd)|
Ref: [lp:2064700](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2064700), [lp:2064701](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2064701)

chore(deps): upgrade ubuntu_widgets to ^0.5.5

---

packages/ubuntu_bootstrap/lib/installer.dart
packages/ubuntu_bootstrap/lib/pages/storage/storage_dialogs.dart
packages/ubuntu_bootstrap/test/installer_test.dart
packages/ubuntu_bootstrap/test/storage/storage_dialogs_test.dart
packages/ubuntu_bootstrap/test/storage/test_storage.dart

@anasereijo this restores the message as a subtitle and looks the same as in 23.10. We can iterate on the design later if you have suggestions for improvements.
Fix #743
UDENG-2941

fix(bootstrap): restore TPM FDE messaging

---

packages/subiquity_client/test/windows_only_wsl_tests.dart

The analyzer complains since the release of the new ubuntu_lints. I think it's safe to ignore here, and we probably should remove that file altogether.

fix(subiquity_client): ignore library annotation for WSL

---

packages/ubuntu_bootstrap/lib/pages/autoinstall/autoinstall_model.dart
packages/ubuntu_bootstrap/lib/pages/autoinstall/autoinstall_page.dart
packages/ubuntu_bootstrap/test/autoinstall/autoinstall_model_test.dart

Adds support for local file paths following the file URI scheme on the autoinstall page (e.g. `file:///home/ubuntu/foo.yaml`.
Successfully tested this with the 24.04 iso.
@anasereijo do we need to update the copy here? As far as I understand this feature is mainly needed for internal purposes.
Fix #754
UDENG-3038

feat(bootstrap): support local file:// URIs on autoinstall page

---

packages/subiquity_client/generator/Makefile
packages/subiquity_client/generator/generator.py

The types.py file in the Subiquity tree is getting difficult to maintain and it would be ideal to split it into multiple files going forward.
Ensure that the generator script can parse content from multiple files.
NOTE: Previously the syntax `./generator.py file1 file2` would parse "file1" and output to "file2". Now, this syntax would parse "file1" and "file2" ; and would output to the standard output. The generator will look for specific file extensions when reading (i.e., *.py) and writing (i.e., *.dart) so there should be no risk of overwriting important files if using the generator incorrectly.

generator: accept multiple .py files as input

---

packages/subiquity_client/generator/test_generator.py

```
python3 -m unittest
/home/loose/projects/canonical/git/ubuntu-desktop-provision/packages/subiquity_client/generator/test_generator.py:159: SyntaxWarning: invalid escape sequence '\$'
self.assertEqual(generator.to_dart(), """
/home/loose/projects/canonical/git/ubuntu-desktop-provision/packages/subiquity_client/generator/test_generator.py:195: SyntaxWarning: invalid escape sequence '\$'
self.assertEqual(generator.to_dart(), """
/home/loose/projects/canonical/git/ubuntu-desktop-provision/packages/subiquity_client/generator/test_generator.py:234: SyntaxWarning: invalid escape sequence '\$'
self.assertEqual(generator.to_dart(), """
/home/loose/projects/canonical/git/ubuntu-desktop-provision/packages/subiquity_client/generator/test_generator.py:309: SyntaxWarning: invalid escape sequence …
```

test(subiquity_client): fix escape sequences in generator test

---

ci/snap/bootstrap/snapcraft.yaml

Seems to be working but the subiquity log has restricted rights so sudo is needed for that work as expected...

Stage the gobject introspection packages needed for ubuntu-bug

---

packages/factory_reset_tools/lib/dbus/factory_reset.dart
packages/factory_reset_tools/pubspec.lock
packages/factory_reset_tools/pubspec.yaml
packages/ubuntu_provision/lib/src/eula/eula_page.dart
packages/ubuntu_provision/lib/src/services/config_service.dart

This patch allows to specify the path where the whitelabel file is stored by using an environment variable. This allows to avoid the problem of running ubuntu-desktop-init from outside a snap container.

Accept environment variable for whitelabel.yaml file path

---

README.md
packages/ubuntu_init/lib/src/init_step.dart

Core desktop doesn't require the UbuntuPro page. Also, at the moment, the Accessibility doesn't work. So those two pages must be allowed to be hiden.

 Allow to hide pages don't needed in core desktop

---

ci/snap/bootstrap/snapcraft.yaml

This reverts commit 08144484541bdfb2d794d31fa1fb1ed544c9e17e.
Getting ubuntu-bug to work would require more work so we are going for an alternative solution

Revert "Stage the gobject introspection packages needed for ubuntu-bug"

---

melos.yaml
packages/subiquity_client/lib/src/types.dart
packages/subiquity_client/lib/src/types.freezed.dart
packages/subiquity_client/lib/src/types.g.dart
packages/subiquity_client/pubspec.yaml
packages/subiquity_client/test/status_monitor_test.dart
packages/ubuntu_bootstrap/test/install/install_model_test.dart

This includes the subiquity [fix](https://github.com/canonical/subiquity/pull/2013) for [lp:2065958](https://bugs.launchpad.net/subiquity/+bug/2065958) in the desktop installer.
I've added a test case that ensures the `LATE_COMMANDS` status is treated correctly, i.e. leaves the installation page in the "installing" state.
Supersedes #781
UDENG-3382

feat(bootstrap): include subiquity late commands fix

---

provd/debian/changelog
provd/debian/provd.postinst
provd/debian/provd.postrm

This is a step towards us replacing GIS by creating the provd user and group in the `postint` and `postrm` stages, though it will be in a future pr to swap to using them entirely (we need to write our own session files first)
- Added `provd` user creation to deb packaging
- Better conditional handling of the creation and removal of groups and `provd` user
- Appended to `debian/changelog`
Closes UDENG-3392

feat(provd): provd user and usergroup now created by deb

---

docs/oem-provisioning-24_04_1.md

This PR suggests some minor changes to the Gnome Initial Setup documentation to improve structure and readability.
The changes include:
- Combining the Introduction and Why Gnome Initial Setup sections to reduce repetition and improve flow. This also helps keep the focus on the `how-to` aspect of the guide, rather than the `explanatory` material, which should be directed towards providing clear instructions to the user.
- Adds a EULA language code section. This was previously referenced in the doc but the section was not present.
- Numbered the two main methods. This is just to improve how the main information can be parsed in GitHub-rendered markdown.
- Several minor changes to improve consistency and clarity: fixes to ambiguous wording, formatting and spelling.
The general structure of …

docs: Gnome Initial Setup revisions

---

ci/snap/reset-tools/snapcraft.yaml
packages/factory_reset_tools/data/polkit.com-canonical-oem-factory-reset-tools.policy
packages/factory_reset_tools/lib/dbus/cmdline.dart
packages/factory_reset_tools/lib/dbus/dbus_daemon.dart
packages/factory_reset_tools/lib/dbus/dbus_local_object.dart
packages/factory_reset_tools/lib/dbus/polkit_agent.dart
packages/factory_reset_tools/lib/dbus/polkit_agent_helper/Makefile
packages/factory_reset_tools/lib/dbus/polkit_agent_helper/helper.c
packages/factory_reset_tools/pubspec.lock
packages/factory_reset_tools/pubspec.yaml

This feature adds polkit authorization before performing factory reset, both in GUI and in CLI
Need to request for an additional `polkit` autoconnect: https://forum.snapcraft.io/t/factory-reset-tools-polkit-autoconnect-request/41632
While implementing polkit interface for GUI applications seems to be straightforward by adding authorization on the server side, doing it in the CLI client is quite a problem.
First, it is necessary to spawn `pkttyagent` by the user program to show the text prompt, but to wait for the `pkttyagent` to be registered onto `polkitd`, `pkttyagent` uses a `--notify` channel which passes a file descriptor that it should close, which, referring to [fwupd implementation](https://github.com/fwupd/fwupd/blob/main/src/fu-polkit-agent.c), uses a pipe to implement. …

feat(reset-tools): Add permission check based on polkit

---

.github/workflows/automatic-doc-checks.yml
.github/workflows/ci.yml
.github/workflows/rebase-for-snap-cicd.yaml

We've now setup the following snap branches for ubuntu-desktop-bootstrap (arrows point to the snap channels to which the builds are uploaded):
`snap/ubuntu-desktop-bootstrap/24.04` -> `24.04/edge`, `latest/candidate` ("legacy", we need to continue maintaining the `latest` since the subiquity version shipped on the 24.04.x ISOs uses that track for the refresh mechanism)
`snap/ubuntu-desktop-bootstrap/main` -> `24.10/edge` (once we start working on features for 25.04, we'll add a `snap/ubuntu-desktop-bootstrap/24.10` branch)
This PR removes 'bootstrap' from the 'rebase' workflow that creates the ephemeral `ci/bootstrap` branch, which is now no longer used. We'll migrate ubuntu-init and the reset-tools separately.
We'll also need to introduce development branches for released versions of the …

ci: move ubuntu-desktop-bootstrap to new branch setup

---

snap/snapcraft.yaml

Includes the new mascot and logos from #809 as well as the latest subiquity fixes from the `ubuntu/noble` branch (#807) (I'll open a follow-up PR tomorrow to track `ubuntu/main` and pull in the latest subiquity changes here).

feat: release new version with updated mascot and logo

---

snap/snapcraft.yaml

includes:
- track subiquity's main branch (#811)
- replace mascot on try-or-install-page (#812)

chore: update refs for bootstrap, curtin, probert

---

docs/oem-provisioning-24_04_1.md

Adding a section on how to install additional language packs to appear in GIS via running late-commands in the `autoinstall.yaml`
This is doubled up as its applicable to two flow's

docs: adding how to add language packs in autoinstall.yaml

---

README.md

Adds a section to the README that explains multiple versions for
multiple snaps can be build from this monorepo.
UDENG-4451

docs: include branch setup for building snaps in README

---

snap/hooks/configure
snap/local/subiquity-server
snap/snapcraft.yaml

Port of https://github.com/canonical/subiquity/pull/2073 to ubuntu-desktop bootstrap.

feat: Inherit Subiquity's ability to configure block probing timeout

---

snap/snapcraft.yaml

We removed cloud-init from the Subiquity snap in commit [0]. This can now be removed from the udb snap too.
[0] afcd2b364a33dcd5bacecee4a7e0f285b87ae2b2

unstage cloud-init from the snap

---

scripts/subiquity-check.sh

I'd like to propose an additional check to the `subiquity-check` script to check for any stage-packages differences. 
Is this the right branch to open the PR against? Or should it go against `main`?
I skip comparing the WSL specific packages because that's not something subiquity specifies and I'm not sure about the details on why those are under `subiquitydeps` in particular or if those still needs to be there.

ci: subiquity-check check stage-packages

---

snap/snapcraft.yaml

Cleans up the `stage-packages` in the snapcraft.yaml to match subiquity's list. See #827.

chore: remove unused stage-packages

---

packages/ubuntu_bootstrap/lib/services/identity_service.dart
packages/ubuntu_bootstrap/test/services/identity_service_test.dart

This fixes a bug where a password containing non-ASCII characters set during the installation would be rejected when booting the newly installed system.
As Dart [`String`](https://api.dart.dev/stable/3.5.3/dart-core/String-class.html)s consist of UTF-16 encoded code units, the SHA-512 crypt hash computed with [`crypt.dart`](https://pub.dev/packages/crypt) doesn't match with the one computed when the user logs in, where the encoding will [default to UTF-8](https://github.com/canonical/ubuntu-desktop-provision/blob/4a1c55e84cd0a3955c7e2b9d77b212a1632bf0f6/packages/ubuntu_provision/lib/src/locale/locale_model.dart#L71-L75).
Fix #831
UDENG-4710

fix: use UTF-8 encoding for password hashing

---

packages/ubuntu_bootstrap/lib/services/identity_service.dart
packages/ubuntu_bootstrap/test/services/identity_service_test.dart

Backport of #835 to `ubuntu/24.04`

fix(24.04): use UTF-8 encoding for password hashing

---

snap/snapcraft.yaml

includes subiquity updates from #830 and password encoding fix from #835

chore: update refs for bootstrap, subiquity and curtin

---

.github/workflows/snap.yaml

Adds a snapcraft workflow to the CI that runs on pushes and pull requests to `snap/**` branches.
I'd also add this to the other `snap/**` branches.

ci: add snap workflow

---

snap/snapcraft.yaml

Ensure subiquity-server and ubuntu-desktop-bootstrap apps have PATH_ORIG, PYTHON_ORIG, and PYTHONPATH_ORIG environment variables. Lacking these causes usage of subiquity's system_scripts to fail to find the right python _outside_ of the snap. This is currently causing installs to fail on daily desktop-builds.
Also remove LD_LIBRARY_PATH_ORIG since it's not needed anymore.
The rational for removing LD_LIBRARY_PATH is mostly that we don't need it. However, after injecting a new snap to test these changes I found subiquity struggling to replace LD_LIBRARY_PATH_ORIG because LD_LIBRARY_PATH wasn't set.   LD_LIBRARY_PATH_ORIG is empty, which means the control flow in the environment cleaner function executes [this line](https://github.com/canonical/subiquity/blob/a57ed5a5e3ba1fd2212fae3c2f3e84cc …

snapcraft: Fix *_ORIG variables

---

SECURITY.md

Quoting SEC0026 - SSDLC
> SECURITY.md (V1.1)
> Any public repository must also include a SECURITY.md file in the root directory, which educates users/contributors on
> how to report a security concern.
The content of the file is based on the template referenced in the spec and what other Canonical repository are already using

docs: Add instructions on how to report security issues

---

snap/snapcraft.yaml

os-prober from the archive is well-behaved now, and is providing the needed answers where staged os-prober is not.
LP: #[2077520](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2077520)

snapcraft: unstage os-prober

---

packages/ubuntu_bootstrap/integration_test/screenshot_test.dart
packages/ubuntu_bootstrap/integration_test/ubuntu_bootstrap_test.dart
packages/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_localizations.dart
packages/ubuntu_init/integration_test/e2e_test.dart
packages/ubuntu_init/integration_test/screenshot_test.dart
packages/ubuntu_init/integration_test/ubuntu_init_test.dart
packages/ubuntu_provision_test/lib/src/bootstrap_tester.dart
packages/ubuntu_provision_test/lib/src/init_tester.dart
packages/ubuntu_provision_test/lib/src/provision_tester.dart

A small refactor to move repeated navigation functions into their test functions for better test readability to help me get more comfortable with navigating the installer project :slightly_smiling_face:

refactor: move tester navigation out of integration tests

---

.github/workflows/check-snap-label.yaml
.github/workflows/snap-release.yaml

This PR adds two github workflows that allow us to automatically raise snap build PRs (`snap/*` branches) driven by labels on mainline PRs.
- `check-snap-label.yaml`
Checks if mainline PRs are labeled with at least one of:
- `snap/ubuntu-desktop-bootstrap`
- `snap/ubuntu-desktop-init`
- `snap/factory-reset-tools`
- `snap/none` (used for PRs that shouldn't trigger any snap release PRs, e.g. documentation changes, ..)
- `snap-release.yaml`
- Runs when a PR is merged into a mainline branch
- Parses the labels from the merged PR and translates them into the names of the release branches, e.g. `snap/ubuntu-desktop-bootstrap` -> `snap/ubuntu-desktop-bootstrap/main` for a PR targeting `main`, or `snap/ubuntu-desktop-bootstrap` -> `snap/ubuntu-desktop-init/24.04` for a PR targeting `ubuntu/24.04` …

ci: release automation

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
README.md

- Adds issue templates for bug reports (and when a bug should be reported to subiquity) and enhancement.
- Updates the README to distinguish between UI bugs and Backend bugs, which should be reported to subiquity.
You can preview what these options look like on my branch [here](https://github.com/matthew-hagemann/ubuntu-desktop-provision/issues/new/choose)

Feat: add issue templates

---

.gitmodules

LP: #2088978 shows a SerializationError related to parsing of the new install-sources format, which includes information about what kernel to use.
Pick up subiquity main again, which we should do anyway but also because it knows how to work with the new install-sources format.

chore(deps): track subiquity main

---

.github/workflows/snap-release.yaml

For pull requests raised from forked repositories, the `GITHUB_TOKEN` only comes with `read` permissions by default. This PR adds `write` permissions for the repository contents, so that the job can create/modify the release branch.

ci: add write permissions for the snap release job

---

.github/workflows/snap-release.yaml

Apparently #870 wasn't enough to fix the permission issue for the snap release job. I had another look at the [documentation](https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#token), which suggests adding `pull-requests: write` as well.

ci: add `pull-requests: write` permission to snap-release job

---

.gitmodules

Temporarily track a different branch, to pickup a fix for install- sources but hold off of core24 for the moment.
This branch is not intended to be updated and should only be used until core24 is ready.
If you have core24 support sorted out please reject this PR.

chore(deps): track subiquity main-core22

---

snap/snapcraft.yaml

Includes #874 to build ubuntu-desktop-bootstrap with the subiquity changes needed for plucky, but still based on core22.

feat: build core22-based installer for plucky

---

apps/ubuntu_bootstrap/lib/app.dart
apps/ubuntu_bootstrap/lib/app/installation_step.dart
dev-docs/adding-a-new-page-to-the-installer.md

Based on my learnings from stubbing out landscape integratino in #882, I have put together some `dev-docs` outlining the broad steps required for adding a new page to the insatller, as well as adding some doc comments on some relevant dart components that did not have any.

docs: adding dev-docs for adding a new page to the installer

---

.github/workflows/snap-release.yaml

This renames the CI automation release branches opened by the bot from e.g. `snap/ubuntu-desktop-bootstrap/main-release` to `release/snap/ubuntu-desktop-bootstrap/main` so that they are no longer affected by the `snap/*` branch protection rules that prevent the bot from updating the release branches.

ci: rename release branch to avoid branch protection issues

---

.github/workflows/ci.yml

Includes subiquity fixes from https://github.com/canonical/subiquity/pull/2125 needed by the OEM team.

fix: include subiquity fixes for OEM

---

packages/ubuntu_provision/pubspec.yaml

Currently the CI [fails](https://github.com/canonical/ubuntu-desktop-provision/actions/runs/12812302578) on `main` due to a breaking change in `pdfrx`:
the package now seems to assume Flutter >=3.27 without having changed its dependencies.

chore: pin pdfrx due to breaking changes

---

provd/go.mod

Needed to fix two vulnerabilities:
```
Vulnerability #1: GO-2025-3420
Sensitive headers incorrectly sent after cross-domain redirect in net/http
More info: https://pkg.go.dev/vuln/GO-2025-3420
Standard library
Found in: net/http@go1.22.5
Fixed in: net/http@go1.22.11
Example traces found:
#1: internal/services/telemetry/telemetry.go:38:31: telemetry.sysmetricsImpl.SendDecline calls sysmetrics.SendDecline, which eventually calls http.Client.Do
Vulnerability #2: GO-2025-3373
Usage of IPv6 zone IDs can bypass URI name constraints in crypto/x509
More info: https://pkg.go.dev/vuln/GO-2025-3373
Standard library
Found in: crypto/x509@go1.22.5
Fixed in: crypto/x509@go1.22.11
Example traces found:
#1: internal/testutils/systembus.go:35:10: testutils.StartLocalSystemBus calls sync.Once.Do, which …
```

chore: bump go toolchain

---

provd/go.mod

chore: bump go toolchain (24.04)

---

apps/ubuntu_bootstrap/lib/pages/storage/bitlocker/bitlocker_page.dart
apps/ubuntu_bootstrap/test/installer_wizard_test.dart

Currently, we show the "Bitlocker" page and stop the user from continuing the installation even when selecting the "Erase disk and install" guided target. Since subiquity is capable of erasing the entire disk and installing Ubuntu in this case, we shouldn't display the page at all and let the user continue instead.
[lp:2045750](https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/2045750)
UDENG-5912

fix: don't block 'erase and install' if bitlocker is detected

---

packages/ubuntu_bootstrap/lib/pages/storage/storage_wizard.dart
packages/ubuntu_bootstrap/test/installer_wizard_test.dart

#929 for `ubuntu/24.04`
UDENG-5912

fix: don't block 'erase and install' if bitlocker is detected (24.04)

---

.github/workflows/ci.yml

This was originally added to make it easier for a contractor to pull a pre-built debian package of provd. Now that provd is in launchpad and no-one on the team uses ARM64 for dev work, these CI steps are redundant.

chore: removing provd deb package build and upload

---

snap/snapcraft.yaml

chore: release snap with subiquity fixes for 24.04.2

---

provd/go.mod
provd/tools/go.mod

Fixes https://github.com/canonical/ubuntu-desktop-provision/actions/runs/13186877081/job/36810990501?pr=917#step:4:616

chore: bump go toolchain versions

---

apps/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_model.dart
apps/ubuntu_bootstrap/test/storage/manual/manual_storage_model_test.dart
packages/subiquity_client/generator/generator.py
packages/subiquity_client/lib/src/types.dart
packages/subiquity_client/lib/src/types.freezed.dart
packages/subiquity_client/lib/src/types.g.dart
packages/subiquity_client/test/types_test.dart

UI changes to support https://github.com/canonical/subiquity/pull/2157
Screencast using probe data and curtin as mentioned in the PR above:
[Screencast From 2025-02-11 11-34-16.webm](https://github.com/user-attachments/assets/663e11f3-bc98-467c-b908-93147bb14fa3)
In this case `/dev/sda` is marked as `unsupported`, so the UI blocks adding/removing/modifying the disk's partitions and setting it as the boot device. Reformatting the entire disk works as usual, though.
@ogayot FYI
UDENG-5999

feat: don't allow modification of unsupported disks

---

provd/.golangci.yaml

Fixes the CI failure coming from the go-sanity check.
See https://github.com/ubuntu/authd/commit/a127b5d418494bc1e1cd35a38127f9301247d718
```
Go: Code sanity
Failed to run: Error: Command failed: /home/runner/golangci-lint-1.57.2-linux-amd64/golangci-lint config verify
jsonschema: "" does not validate with "/additionalProperties": additionalProperties 'nolintlint' not allowed
Error: the configuration contains invalid elements
Usage:
golangci-lint config verify [flags]
Global Flags:
--color string   Use color when printing; can be 'always', 'auto', or 'never' (default "auto")
-c, --config PATH    Read config from file path PATH
-h, --help           Help for a command
--no-config      Don't read config file
-v, --verbose        Verbose output
Failed executing command with error: the …
```

Fix: invalid golangci-lint config

---

snap/snapcraft.yaml

chore: bump dependencies for bootstrap and curtin

---

apps/ubuntu_bootstrap/lib/pages/source/on_battery_snackbar.dart

Quick change to lighten the "Warning" text that appears when on battery power to have a better contrast ratio. The snack bar is always the same color so using the Yaru dark theme error color instead seems fitting.
<details>
<summary>Screenshot</summary>
</details>
---
UDENG-6292

fix: Lighten "Warning" text in battery toasts

---

apps/ubuntu_bootstrap/lib/services/storage_service.dart
apps/ubuntu_bootstrap/test/services/storage_service_test.dart

I've explored a few different options for fixing this, but ultimately decided that resetting the storage before setting the guided target (which is currently being done when the confirmation page is loaded) is the simplest solution.
My preferred solution would be posting to `/storage/v2/guided` once the user finishes the storage configuration, but since all pages in the storage wizard potentially affect the request we need to send, we'd have to do the request either on the last page in the wizard (currently the 'passphrase' page) or on the first page that follows just after the storage wizard (currently the 'identity' page). Both seem like arbitrary choices and we'd have to move the logic around again in case these pages are moved to a different place.
If we find some time to refactor the …

fix: reset storage before setting a guided target

---

.gitmodules

This PR targets the newly created `ubuntu/25.04` branch and updates the `.gitmodules` file to track https://github.com/canonical/subiquity/tree/ubuntu/plucky.
UDENG-6467

deps: track subiquity's plucky branch for 25.04

---

apps/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_model.dart
apps/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_widgets.dart
apps/ubuntu_bootstrap/test/storage/manual/manual_storage_page_test.dart
apps/ubuntu_bootstrap/test/storage/manual/test_manual_storage.dart
apps/ubuntu_bootstrap/test/storage/manual/test_manual_storage.mocks.dart

Fixes a bug on the manual storage page where pressing the `-` button (to delete a partition) multiple times in quick succession, can lead to an error in subiquity. To prevent sending the same request twice before subiquity responds, this PR adds some logic to disable the button while we wait for the server reply. We should consider introducing a proper UI loading state in the future, though.
Example with artificial delay in subiquity:
```diff
diff --git i/subiquity/server/controllers/filesystem.py w/subiquity/server/controllers/filesystem.py
index a12b6fe8..1b065b97 100644
--- i/subiquity/server/controllers/filesystem.py
+++ w/subiquity/server/controllers/filesystem.py
@@ -1482,6 +1482,7 @@ class FilesystemController(SubiquityController, FilesystemManipulator):
self, data: …
```

fix: disable delete partition button while waiting for reply

---

packages/ubuntu_provision/lib/src/widgets/journal_view.dart

Previous changes resulted in the hover color of the journal log during install to be white. This changes the hover color to transparent.
Fixes #1006
---
UDENG-6566

fix: Correct journal log's hover color

---

apps/ubuntu_bootstrap/lib/pages/storage/passphrase/passphrase_model.dart
apps/ubuntu_bootstrap/test/storage/passphrase/passphrase_model_test.dart
apps/ubuntu_bootstrap/test/storage/passphrase/test_passphrase.mocks.dart

fix: clear passphrase when not using a corresponding capability

---

apps/ubuntu_bootstrap/lib/pages/confirm/confirm_model.dart
apps/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart
apps/ubuntu_bootstrap/test/confirm/confirm_model_test.dart
apps/ubuntu_bootstrap/test/confirm/test_confirm.dart
apps/ubuntu_bootstrap/test/confirm/test_confirm.mocks.dart

In #969 we've changed the behavior of the `confirmModel` to provide a list of *all* disks instead of only those that have been modified in order to include unchanged partitions in the table on the confirmation page. However, the 'Installation disk' entry on that page still needs access to a list of modified disks - this PR (re-)adds this property.
Fix #1012
UDENG-6572

fix(confirm): restore modified disks

---

apps/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart
packages/subiquity_client/lib/src/types.dart
packages/subiquity_client/lib/src/types.freezed.dart
packages/subiquity_client/lib/src/types.g.dart
packages/subiquity_client/test/types_test.dart

This makes use of the `effectiveMount` and `effectiveFormat` properties recently added to subiquity's API.
I've also moved the whole partition summary table into a separate widget to clean up the code a bit.
Fix #1001
UDENG-6530

fix: show mountpoint and partition format for ZFS/LVM setups

---

apps/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart

This should now match the alignment in the Figma designs.
Fix: #1011 
UDENG-6573

fix: align remaining confirm page entries to summary table

---

snap/snapcraft.yaml

Include `snapcraft.yaml` fix from #1031 in `snap/ubuntu-desktop-bootstrap/main`

fix: Install libgles2 (LP: #2106101)

---

.github/workflows/ci.yml

Supersedes #938.
See https://github.com/ubuntu/app-center/pull/1906
I don't think the go coverage data is picked up correctly yet, but I'd continue on fixing those issues after getting a working workflow in place.
Low coverage result in TiCS is due to generated files and l10n files - we'll need to ask tiobe to explicitly exclude those in the backend.
UDENG-5819

ci: setup TiCS workflow

---

apps/ubuntu_bootstrap/pubspec.lock
apps/ubuntu_bootstrap/pubspec.yaml
apps/ubuntu_init/pubspec.lock
apps/ubuntu_init/pubspec.yaml
packages/ubuntu_provision/pubspec.yaml

Includes https://github.com/canonical/subiquity/pull/2193 in `ubuntu/25.04`.
I had to pin `timezone_map` since we've bumped the Flutter version in `ubuntu-flutter-plugins` (it's a `git` dependency, since it isn't published on pub.dev).

chore: include subiquity fix for LP:#2105480

---

apps/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart

In #1020 I've mistakenly replaced `partition.wipe != null` with `!partition.preserved` during a refactor. This PR reverts the logic to its previous state.
Fix [lp:2107208](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2107208)
UDENG-6769

fix(confirm_page): list partitions as 'formatted' when `wipe`d

---

.github/workflows/ci.yml

Similar to what we previously did in the app-center - this step is no longer required due to some changes on the tiobe side.
UDENG-7356

fix(ci): remove cleanup step

---

packages/ubuntu_provision/lib/src/timezone/timezone_page.dart

The timezone map already seems to ignore tab navigation (desired), so this just gives it a label of the currently selected location for convenience.
---
Audit 1858984
UDEAA-122

fix(a11y): Add semantic label to timezone map

---

.github/workflows/pr.yaml

Since there's now an org-wide CLA action, the local workflow is obsolete.

ci: remove local CLA check

---

packages/ubuntu_provision/lib/src/keyboard/keyboard_page.dart

Previously, the label was not read by screen readers.
---
UDENG-7685

fix(a11y): Associate keyboard variant button with label

---

.github/workflows/ci.yml

We're about to merge a breaking change in the `go/code-sanity` GitHub Action ([use of golangci-lint v2 instead of v1](https://github.com/canonical/desktop-engineering/pull/75)), so to avoid breaking the CI, we need to switch to `go/code-sanity@v1` instead of `go/code-sanity@main`.
Once the change has been merged, I will prepare a follow-up PR to migrate the `.golangci.yaml` to the v2 format and use `go/code-sanity@v2`.
UDENG-7801

ci: Use go/code-sanity@v1

---

packages/ubuntu_wizard/lib/src/wizard_theme.dart

Previously the border color was accidentally being overridden by other theme data.

fix: Fix input decoration colors

---

apps/ubuntu_bootstrap/lib/services/environment_variable_service.dart
apps/ubuntu_bootstrap/test/services/environment_variable_service_test.dart

This inverts the current default behavior, which was accidentally setup to be false by default

fix: useTls should be true by default, not false

---

snap/snapcraft.yaml

To mitigate the flickering issue present on Flutter 3.35, let's use the software renderer for now.

feat: force software rendering while flutter rendering issue persists
