packages/ubuntu_bootstrap/lib/pages/install/install_model.dart
Don't assume that slide assets are in `flutter_assets/packages/ubuntu_bootstrap/assets/slides` because this won't be the case if `ubuntu_bootstrap` itself was made an app for development and testing purposes. In that case, the assets would be in `flutter_assets/assets/slides`. Furthermore, we should also pre-cache slide assets that have been overridden by flavors and OEMs, which is better achieved by iterating the asset manifest than looking into specific directories on the file system.
=> refactor(bootstrap): generalize slide asset pre-caching

packages/ubuntu_bootstrap/.metadata, packages/ubuntu_bootstrap/linux/.gitignore, packages/ubuntu_bootstrap/linux/CMakeLists.txt, packages/ubuntu_bootstrap/linux/flutter/CMakeLists.txt, packages/ubuntu_bootstrap/linux/main.cc, packages/ubuntu_bootstrap/linux/my_application.cc, packages/ubuntu_bootstrap/linux/my_application.h, packages/ubuntu_bootstrap/pubspec.yaml
Mainly for development and testing purposes.
=> feat(bootstrap): add app runner for ubuntu_bootstrap

packages/ubuntu_init/lib/src/init_services.dart, packages/ubuntu_init/lib/src/init_wizard.dart, packages/ubuntu_init/test/init_wizard_test.dart
The network page does not depend on Subiquity and thus, can be supported in the init-phase.
=> feat(init): add network

packages/ubuntu_init/lib/src/init_services.dart, packages/ubuntu_init/lib/src/init_wizard.dart, packages/ubuntu_init/test/init_services_test.dart, packages/ubuntu_init/test/init_wizard_test.dart, packages/ubuntu_provision/lib/src/theme/theme_page.dart
The theme page does not depend on Subiquity and thus, can be supported in the init-phase.
=> feat(init): add theme

.github/workflows/ci.yml, packages/ubuntu_init/integration_test/ubuntu_init_test.dart, packages/ubuntu_init/pubspec.yaml, packages/ubuntu_provision/pubspec.yaml, packages/ubuntu_provision_test/lib/src/expect.dart, packages/ubuntu_provision_test/lib/src/fake_init.dart, packages/ubuntu_provision_test/lib/ubuntu_provision_test.dart, packages/ubuntu_provision_test/pubspec.yaml
Runs with the keyfile backend for GSettings and a fake D-Bus server to make it safe to run the test in any environment.
=> test: ubuntu_init integration test

packages/ubuntu_bootstrap/integration_test/ubuntu_bootstrap_test.dart, packages/ubuntu_bootstrap/lib/pages/storage/security_key/security_key_model.dart, packages/ubuntu_bootstrap/lib/pages/storage/storage_dialogs.dart, packages/ubuntu_bootstrap/lib/pages/storage/storage_model.dart, packages/ubuntu_bootstrap/lib/pages/storage/storage_page.dart, packages/ubuntu_bootstrap/lib/services/storage_service.dart, packages/ubuntu_bootstrap/test/services/storage_service_test.dart, packages/ubuntu_bootstrap/test/storage/storage_dialogs_test.dart, packages/ubuntu_bootstrap/test/storage/storage_model_test.dart, packages/ubuntu_bootstrap/test/storage/storage_page_test.dart, packages/ubuntu_bootstrap/test/storage/test_storage.dart, packages/ubuntu_bootstrap/test/storage/test_storage.mocks.dart, packages/ubuntu_bootstrap/test/test_utils.mocks.dart, packages/ubuntu_provision_test/lib/src/bootstrap_tester.dart
This is a preparation step towards ZFS & TPM/FDE support. These options are reported from Subiquity as guided capabilities.
Ref:
- https://github.com/canonical/ubuntu-desktop-installer/issues/417
- https://github.com/canonical/ubuntu-desktop-installer/issues/2278
=> refactor(bootstrap): use guided capabilities for "advanced features"

README.md
Originates from:
- https://github.com/canonical/ubuntu-desktop-installer/issues/2194
=> chore(readme): diagram

.github/workflows/pr.yaml
Drop the broken semantic PR title check.
=> ci: clean up

packages/ubuntu_init/lib/src/init_app.dart, packages/ubuntu_init/lib/src/init_wizard.dart
ubuntu-welcome needs to write a file when the wizard is done.
=> feat(init): on done callback

packages/ubuntu_bootstrap/lib/slides/default_slides.dart
Fix https://github.com/canonical/ubuntu-desktop-installer/issues/2337
=> feat(slides): thunderbird+libreoffice included -> available

packages/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_localizations_sk.dart, packages/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_localizations_sv.dart, packages/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_localizations_tr.dart, packages/ubuntu_init/lib/src/l10n/ubuntu_init_localizations_sk.dart, pubspec.lock
Closes https://github.com/canonical/ubuntu-desktop-provision/issues/146
=> chore(deps): bump subiquity_client.dart to `ada1bc0`

packages/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_localizations_uk.dart, packages/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_uk.arb
This is a rebased version of #172 - thanks @alexmazaltov!
=> feat: add alexmazaltov's translations

README.md, melos.yaml, packages/ubuntu_provision/lib/src/services/config_service.dart, packages/ubuntu_provision/pubspec.yaml, packages/ubuntu_provision/test/services/config_service_test.dart
=> feat: Drop TOML and JSON support for config files

snap/snapcraft.yaml
see https://github.com/canonical/ubuntu-desktop-installer/pull/2397
P.S. maybe we could improve the CI for this a bit - doesn't make much sense to run the entire CI in this branch, we should just run the snap job here, I guess
=> feat: stage libelf1

codecov.yaml
Added a 5% threshold to the codecov check
Added a minimum target of 80% to keep us from dropping too far
Closes #209
=> ci(codecov): Add change failour thresholds

.github/workflows/snap.yaml, .github/workflows/subiquity.yaml
Re-adds the consistency check for the subiquity dependencies in the snapcraft.yaml, previously used [here](https://github.com/canonical/ubuntu-desktop-installer/blob/bae891ad998aed8b0f0be294c1643b3e8d98e819/.github/workflows/ci.yml#L96-L103).
=> feat(ci): add subiquity integration check

snap/local/postinst.d/99_install_provd
~~@matthew-hagemann for this to work, you'll need to copy the package in the ppa to the 'noble' series (this can wait until you're back from the holidays, of course!).~~
Edit: done, thanks!
Should be good to go now
Close #252
=> feat: add postinst script to install provd from ppa

README.md
=> docs: update config schema and repo structure in README

.gitmodules
This should make sure renovate does its job again :)
=> feat: track subiquity's main branch

snap/snapcraft.yaml
=> chore: update subiquity deps

packages/ubuntu_bootstrap/lib/services/refresh_service.freezed.dart, packages/ubuntu_provision/lib/services.dart, packages/ubuntu_provision/lib/src/services/desktop_service.dart, packages/ubuntu_provision/test/services/desktop_service_test.dart
Cherry-picked `DesktopService` fixes from #352.
=> feat: handle/log errors in `DesktopService`

melos.yaml, packages/subiquity_client/pubspec.yaml, packages/ubuntu_bootstrap/pubspec.yaml, packages/ubuntu_init/pubspec.yaml, packages/ubuntu_provision/lib/src/network/hidden_wifi_view.dart, packages/ubuntu_provision/lib/src/network/network_page.dart, packages/ubuntu_provision/lib/src/network/wifi_view.dart, packages/ubuntu_provision/pubspec.yaml, packages/ubuntu_provision_test/pubspec.yaml, packages/ubuntu_utils/pubspec.yaml, packages/ubuntu_wizard/pubspec.yaml
Before the `WifiView` crashed when another radio button was chosen due to how flex was set up on it.
=> fix: wifi_views to not be flexible in a non-constrained context

packages/ubuntu_wizard/lib/src/wizard_button.dart, packages/ubuntu_wizard/test/wizard_page_test.dart
See https://github.com/canonical/ubuntu-desktop-provision/pull/341#discussion_r1479915081
=> fix(ubuntu_wizard): restore `hasPrevious` behavior

packages/ubuntu_provision/lib/src/services/config_service.dart, packages/ubuntu_provision/lib/src/services/page_config_service.dart, packages/ubuntu_provision/lib/src/services/theme_variant_service.dart, packages/ubuntu_provision/test/services/config_service_test.dart, packages/ubuntu_provision/test/services/page_config_service_test.dart, packages/ubuntu_provision/test/services/theme_variant_service_test.dart, packages/ubuntu_provision/test/test_utils.mocks.dart, packages/ubuntu_utils/lib/src/yaml_map_extension.dart, packages/ubuntu_utils/lib/ubuntu_utils.dart, packages/ubuntu_utils/pubspec.yaml
=> feat: Merge custom whitelabel file with the default

packages/ubuntu_provision/assets/whitelabel.yml, packages/ubuntu_provision/lib/src/services/page_config_service.dart, packages/ubuntu_provision/test/services/page_config_service_test.dart
I had to move the `try-or-install` option around a bit. I think it's a bit clearer now - please complain if it's not!
=> feat(provision): disable 'visible' setting in config

packages/ubuntu_provision/lib/src/providers/page_images.dart, packages/ubuntu_provision/test/providers/page_images_test.dart
Currently the page image configuration only works when specified like this
```yaml
pages:
locale:
image: "/foo.png"
```
This PR removes the need for the leading `/` and improves the test.
=> fix(whitelabel): don't require 'absolute' paths for images

.github/workflows/rebase-ci-bootstrap.yaml, .github/workflows/rebase-ci-init.yaml
I think this is all that's needed to fix [this](https://github.com/canonical/ubuntu-desktop-provision/actions/runs/7963091593/job/21737980408).
=> fix(ci): update submodules in rebase workflows

packages/ubuntu_provision/lib/src/network/network_page.dart, packages/ubuntu_provision/lib/src/widgets/horizontal_page.dart
Fixed two first issues in #495
=> fix: More flex and padding for NetworkPage

packages/ubuntu_bootstrap/lib/pages/source/codecs_and_drivers_page.dart, packages/ubuntu_bootstrap/test/source/codecs_and_drivers_page_test.dart
https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2056608
=> fix(bootstrap): text overflows on codecs+drivers page

packages/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart, packages/ubuntu_bootstrap/lib/pages/storage/storage_page.dart, packages/ubuntu_bootstrap/test/storage/storage_page_test.dart
=> feat(bootstrap): remove boxes and version numbers from storage options

packages/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart
=> fix(bootstrap): use correct font size for headers

packages/ubuntu_bootstrap/lib/pages/storage/storage_dialogs.dart
=> fix: Add experimental badge to TPM option

packages/ubuntu_bootstrap/lib/pages/autoinstall/autoinstall_page.dart, packages/ubuntu_bootstrap/lib/pages/source/source_selection_page.dart, packages/ubuntu_bootstrap/lib/pages/try_or_install/try_or_install_page.dart, packages/ubuntu_bootstrap/lib/widgets/option_button.dart
Ref: #495
UDENG-2506
[Screencast from 2024-03-19 16-17-45.webm](https://github.com/canonical/ubuntu-desktop-provision/assets/113362648/4b8c8b48-bae6-4965-80b7-0d8b3fc528d7)
=> feat(bootstrap): make option button style more consistent

packages/ubuntu_bootstrap/lib/pages/autoinstall/autoinstall_page.dart, packages/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart, packages/ubuntu_bootstrap/lib/pages/rst/rst_page.dart, packages/ubuntu_bootstrap/lib/pages/source/codecs_and_drivers_page.dart, packages/ubuntu_bootstrap/lib/pages/source/source_selection_page.dart, packages/ubuntu_bootstrap/lib/pages/storage/passphrase/passphrase_page.dart, packages/ubuntu_bootstrap/lib/pages/storage/storage_page.dart, packages/ubuntu_bootstrap/lib/pages/try_or_install/try_or_install_page.dart, packages/ubuntu_provision/lib/src/accessibility/accessibility_page.dart, packages/ubuntu_provision/lib/src/active_directory/active_directory_page.dart, packages/ubuntu_provision/lib/src/error/error_page.dart, packages/ubuntu_provision/lib/src/identity/identity_page.dart, packages/ubuntu_provision/lib/src/keyboard/keyboard_page.dart, packages/ubuntu_provision/lib/src/locale/locale_page.dart, packages/ubuntu_provision/lib/src/network/network_page.dart, packages/ubuntu_provision/lib/src/widgets/horizontal_page.dart
[Screencast from 2024-03-19 16-52-15.webm](https://github.com/canonical/ubuntu-desktop-provision/assets/744771/577a26a1-9f0e-4960-9eb5-513a2770566c)
The autoinstall page will be fixed once #536 is rebased on this
=> refactor: Rework HorizontalPage to properly center everything

.gitmodules
After Ubuntu feature freeze for a cycle, a feature freeze branch is created.  Track this ubuntu/noble feature freeze branch while working toward the Noble release.
=> chore: track subiquity ubuntu/noble branch

packages/ubuntu_provision/lib/src/identity/identity_model.dart
Unless you are LENOVO or IBM in which case they have forever put their product names in the 'Version' field instead.
This fixes the default hostname being nonsensical on non-Lenovo systems.
Closes: https://bugs.launchpad.net/bugs/2056167
Closes: https://github.com/canonical/ubuntu-desktop-installer/issues/2394
=> fix: The product name should come from SMBIOS 'Product Name'

packages/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_dialogs.dart, packages/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_model.dart, packages/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_page.dart, packages/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_widgets.dart, packages/ubuntu_bootstrap/lib/pages/storage/manual/storage_columns.dart, packages/ubuntu_bootstrap/lib/pages/storage/manual/storage_selector.dart, packages/ubuntu_bootstrap/lib/pages/storage/manual/storage_types.dart, packages/ubuntu_bootstrap/test/storage/manual/manual_storage_dialogs_test.dart, packages/ubuntu_bootstrap/test/storage/manual/manual_storage_page_test.dart, packages/ubuntu_provision/test/providers/flavor_test.dart
This forces the partition that is chosen as root to be formatted.
=> fix: Always format root partition

provd/debian/changelog, provd/debian/control, provd/debian/copyright, provd/debian/install, provd/debian/launch-desktop-provision-init, provd/debian/provd.install, provd/debian/provd.postinst, provd/debian/provd.postrm, provd/debian/rules, provd/debian/source/lintian-overrides, provd/go.mod
Multiple fixes in the packaging.
=> maint(provd): packaging fixes

snap/snapcraft.yaml
=> feat(snap): path patch for EULA page

packages/ubuntu_bootstrap/lib/pages/autoinstall/autoinstall_page.dart
=> fix: Only show validate button if url is valid

packages/ubuntu_provision/lib/src/locale/locale_page.dart
Fixes https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2061019
=> fix(bootstrap): play welcome sound when finished loading

packages/ubuntu_provision/lib/src/error/error_model.dart, packages/ubuntu_provision/lib/src/error/error_page.dart
[Screencast from 2024-04-12 17-36-59.webm](https://github.com/canonical/ubuntu-desktop-provision/assets/744771/cb8272c8-dc57-4af0-9927-233066b395e4)
=> fix: Improved ErrorPage with larger log window

.github/workflows/ci.yml
Currently we have to do this manually on the weblate branches
=> chore: Generate l10n on weblate PRs

ci/snap/init/snapcraft.yaml
I committed these changes to the `init/ci` branch's `snapcraft.yaml`, but after they didn't reflect in the store request, I realize I should have updated this `snapcraft.yaml` instead :sweat_smile: 
Adds these commits as well as some style changes requested by the store team:
#638
#635
https://forum.snapcraft.io/t/request-for-system-files-interface-multiple-plugs-for-ubuntu-desktop-init/39717
=> Init snap store updates

provd/debian/changelog
Adding in update to debian changelog for releasing the flaky TestQuit fix
=> chore(provd): updating debian changelog

.github/renovate.json
Makes it easier to keep up with subiquity
=> ci(renovate): allow subiquity updates at any time

ci/snap/reset-tools/snapcraft.yaml
remove unused plugs, rename dbus system connections and add dbus session slot for flutter
=> fix(reset-tools): adjust snap connections

packages/ubuntu_bootstrap/test/installer_wizard_test.dart, packages/ubuntu_init/test/init_wizard_test.dart, packages/ubuntu_provision/lib/src/timezone/timezone_page.dart, packages/ubuntu_provision/test/timezone/timezone_page_test.dart
Fixes https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2062531
=> fix(provision): require timezone selection to continue

packages/ubuntu_init/integration_test/screenshot_test.dart, packages/ubuntu_provision_test/lib/src/provision_tester.dart
- removed leading numbers
- re-ordered tests to match figma
- added screenshot for eula and a11y pages
=> feat(init): overhaul screenshot test

ci/snap/reset-tools/snapcraft.yaml
This will change the version of the image into git commit hash, to tell between versions.
=> feat(reset-tools): change version number to git

.github/workflows/pr.yaml
This reverts commit a570050c56c3745d1c0299aeb968e36e60798c0a.
=> feat(ci): re-enable fixed CLA check

packages/ubuntu_init/pubspec.lock
Includes https://github.com/canonical/ubuntu-flutter-plugins/pull/415 to fix [lp:2063575](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2063575).
=> chore(init): update ubuntu_localizations

provd/debian/changelog
ppa has this deb uploaded [here](https://launchpad.net/~matt-hagemann/+archive/ubuntu/provd/+packages)
=> chore(provd): debian changelog for 0.1.4 release

.github/workflows/sync-gh-jira.yaml
Renamed from "Apps" to "Flutter"
=> chore(ci): update jira component

packages/ubuntu_bootstrap/lib/installer.dart, packages/ubuntu_bootstrap/lib/services/keyboard_service.dart, packages/ubuntu_bootstrap/test/services/keyboard_service_test.dart
Quality of life improvement for developers with non-standard keyboard layouts :)
=> feat(bootstrap): don't change keyboard layout in dryrun

GIS.md, README.md
Closes UDENG-3017
Add documentation on how GIS can be triggered by an autoinstall.yaml
Add documentation on how GIS can be triggered via the Flutter installer and a whitelabel.yaml
Link to the documentation from the README.md
=> docs: adding docs on GIS

provd/Makefile, provd/README.md
Adds a Makefile with scripts to setup and boot into a vm setup with ubuntu-desktop-init + provd, booted into the GIS session for easier testing and iteration.
Closes UDENG-3403
=> feat(provd): Makefile for local provd testing in a vm

packages/factory_reset_tools/lib/dbus/reset_media.dart
We received a report that, if using a disk without partition table:
```
sudo dd if=/dev/zero of=/dev/sda bs=512 count=1
sudo mkfs.fat /dev/sda
```
is it is possible to trigger error that USB media remains unformatted.
However, after my investigation I also found that partition unmounted error is not handled properly.  This merge request handles both `org.freedesktop.UDisks2.Error.NotMounted` error and treat it as nothing happened, as well as properly unmounting USB media without partition table.
I am waiting for colleague's response before actual merge.
=> fix(reset-tools/reset_media.dart): fix exceptions on unmounting

snap/snapcraft.yaml
=> feat: release snap with stacked anniversary logo

snap/snapcraft.yaml
includes subiquity updates from #817 and #818
=> feat: release snap with subiquity updates

snap/snapcraft.yaml
includes subiquity updates from #823 and translation updates from #798
=> feat: release snap with l10n and subiquity updates

scripts/subiquity-check.sh
Replicated changes proposed in #827 for the 24.04 builder branch
=> ci: subiquity-check check stage-packages

snap/snapcraft.yaml
=> chore: update refs for bootstrap and subiquity

.github/workflows/ci.yml, melos.yaml
=> ci: upload cobertura coverage report for TiCS

README.md, docs/CONTRIBUTING.md
=> docs: document release automation and snap building

snap/snapcraft.yaml
=> feat: release 24.04 snap with subquity fixes for OEM

packages/ubuntu_provision/lib/src/network/network_page.dart, packages/ubuntu_provision/lib/src/network/wifi_model.dart
Backport of #879 to `ubuntu/24.04`.
=> fix: backport network page fixes

snap/snapcraft.yaml
Includes changes from #930, #921 and #919
=> feat: release 24.04 snap with backported UI fixes

provd/.golangci.yaml, provd/go.mod
I've cherry-picked #957 and bumped the go toolchain to appease the CI
=> feat: golang ci fixes for 24.04

apps/ubuntu_bootstrap/lib/widgets/storage_size_box.dart, apps/ubuntu_bootstrap/test/storage/guided_resize/storage_size_dialog_test.dart
=> fix(manual_storage): respect minimum partition size in editor

snap/local/subiquity-server
See https://github.com/canonical/subiquity/pull/2180
cc @ogayot
=> feat: disable subiquity wlan listener

apps/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart, apps/ubuntu_bootstrap/lib/pages/storage/guided_capabilities_page.dart, apps/ubuntu_bootstrap/lib/widgets/info_badge.dart
Fixes the 'experimental' badge alignment issues as discussed with @juanruitina 
Before:
[Screencast From 2025-03-20 16-07-02.webm](https://github.com/user-attachments/assets/5e995490-05c5-4826-9d9c-fafe8dd5e290)
After:
[Screencast From 2025-03-20 16-08-11.webm](https://github.com/user-attachments/assets/432d703c-4b82-4954-9b78-246b83ada43b)
=> fix: info badge alignment

apps/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart, apps/ubuntu_bootstrap/lib/pages/storage/guided_capabilities_page.dart, apps/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_model.dart, apps/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_widgets.dart, apps/ubuntu_bootstrap/lib/widgets/info_badge.dart, apps/ubuntu_bootstrap/test/storage/manual/manual_storage_page_test.dart, apps/ubuntu_bootstrap/test/storage/manual/test_manual_storage.dart, apps/ubuntu_bootstrap/test/storage/manual/test_manual_storage.mocks.dart
Includes changes from #992 and #993 in `ubuntu/25.04`
=> fix: include fixes for manual storage and info badge alignment in 25.04

snap/local/subiquity-server, snap/snapcraft.yaml
Follow-up to #1026, see also #989.
=> chore: release 24.04 snap with wifi fixes

apps/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_de.arb, apps/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_et.arb, apps/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_localizations_de.dart, apps/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_localizations_et.dart, apps/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_localizations_oc.dart, apps/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_localizations_zh.dart, apps/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_oc.arb, apps/ubuntu_bootstrap/lib/l10n/ubuntu_bootstrap_zh_TW.arb
=> feat: include final translations for 25.04

apps/ubuntu_bootstrap/lib/pages/confirm/confirm_page.dart
=> fix(confirm_page): list partitions as 'formatted' when `wipe`d (#1047)

packages/subiquity_client/lib/src/types.dart, packages/subiquity_client/lib/src/types.freezed.dart, packages/subiquity_client/lib/src/types.g.dart, packages/subiquity_client/test/types_test.dart, packages/ubuntu_bootstrap/lib/pages/storage/manual/manual_storage_model.dart, packages/ubuntu_bootstrap/test/storage/manual/manual_storage_model_test.dart
Backports #943 to `ubuntu/24.04`. See also https://github.com/canonical/subiquity/pull/2199
UDENG-6984
=> feat: backport unsupported disks fix to 24.04

snap/snapcraft.yaml
=> chore: release 24.04 snap with fixes for unsupported disks

snap/snapcraft.yaml
Includes #1127 in the 24.04 snap
=> chore: update ubuntu bootstrap

apps/factory_reset_tools/pubspec.lock, apps/factory_reset_tools/pubspec.yaml, apps/ubuntu_bootstrap/pubspec.lock, apps/ubuntu_bootstrap/pubspec.yaml, apps/ubuntu_init/pubspec.lock, apps/ubuntu_init/pubspec.yaml, melos.yaml, packages/ubuntu_provision/pubspec.yaml, packages/ubuntu_provision_test/pubspec.yaml, packages/ubuntu_utils/pubspec.yaml, packages/ubuntu_wizard/pubspec.yaml, pubspec.lock
Updates yaru to include latest a11y fixes
=> chore: update yaru

.github/workflows/ci.yml, .github/workflows/pr.yaml, melos.yaml
~~Removes~~Updates the local CLA check on ubuntu/24.04 branch, and updates the 22.04 actions to 24.04.
Related: https://github.com/canonical/ubuntu-desktop-provision/pull/1150
=> ci(24.04): Update local CLA to v2

packages/ubuntu_provision/lib/src/locale/locale_page.dart
This pull request significantly improves the accessibility of the locale selection page to comply with WCAG guidelines and provide a better experience for users relying on assistive technologies. The changes address focus management, keyboard navigation, and screen reader support while maintaining the existing functionality and code quality standards.
- **Enhanced semantic labels**: Screen readers now announce "Choose your language:" when entering the language list
- **Usage instructions**: Added semantic hints with clear navigation instructions
- **Position information**: Each language item announces its position (e.g., "English, 1 of 50")
- **Selection feedback**: Screen readers announce when a language is selected
- **Proper Tab cycling**: Focus cycles correctly between language list ↔ …
=> feat(a11y): Enhance accessibility for locale selection page

snap/snapcraft.yaml
=> chore: update bootstrap to include AD fix

apps/factory_reset_tools/linux/my_application.cc
Workaround for [gtk#2599](https://gitlab.gnome.org/GNOME/gtk/-/issues/2599)
Fix [LP: 2124253](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2124253)
- Detect if 3.24.9 <= gtk3 version < 3.24.42 && running on wayland. If so, correct pixel size by scale
- Maximize window rather than entering fullscreen when default window size > workarea
Tested on a 10" tablet with integer scale 200% and Dell XPS 13 9340 with integer scale 200%
=> Add workaround for gtk #2599

snap/snapcraft.yaml
Includes translations from #1075 in the desktop installer snap
UDENG-8174
=> chore: include updated translations in snap
